-- before delete
DROP TRIGGER T_AFT_DEL_LVNT_UPD_TOTALVNT;
-- delete vente will cascade to delete credit => afect sold client
DROP TRIGGER T_AFT_DEL_CREDIT_UPD_CLIENT;
-- delete vente will cascade to delete reglement => afect sold client
DROP TRIGGER T_AFT_DEL_REGL_UPD_CLIENT;
-- delete
DELETE FROM VENTE WHERE "DATE" < '2016-10-01';

-- after delete
CREATE TRIGGER T_AFT_DEL_LVNT_UPD_TOTALVNT
AFTER DELETE ON LIGNE_VNT
REFERENCING OLD ROW AS DEL_LVNT
FOR EACH ROW
    UPDATE VENTE SET 
        TOTAL = TOTAL - DEL_LVNT.TOTAL_LVNT
    WHERE ID = DEL_LVNT.ID_VNT;


CREATE TRIGGER T_AFT_DEL_CREDIT_UPD_CLIENT
AFTER DELETE ON CREDIT_CL
REFERENCING OLD ROW AS OLD_CREDIT
FOR EACH ROW
    UPDATE CLIENT SET DETTE = DETTE - OLD_CREDIT.MONTANT
    WHERE CLIENT.ID = OLD_CREDIT.ID_CL;


CREATE TRIGGER T_AFT_DEL_REGL_UPD_CLIENT
AFTER DELETE ON REGLEMENT_CL
REFERENCING OLD ROW AS OLD_REGL
FOR EACH ROW
    UPDATE CLIENT SET DETTE = DETTE + OLD_REGL.MONTANT
    WHERE CLIENT.ID = OLD_REGL.ID_CL; 
