/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CtegoriePanel.java
 *
 * Created on 17/10/2009, 11:25:33 ص
 */
package panels.crud;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import myComponents.MyJFrame;
import panels.maj.MajProduitPanel;

/**
 *
 * @author alilo
 */
public class InventaireStockPanel extends ListeProduitsPanel {

    private ListeLotsEnStockPanel enStockList;
    private final MajProduitPanel majProdPanel = new MajProduitPanel(this).setEnableGestStock(false);

    public InventaireStockPanel(Container owner) {
        super(owner, false, false);
        initComponents();
        setMajPanel(majProdPanel);
        add(mainPanel, BorderLayout.CENTER);
        initEnStockPanel();
        doOnPress(KeyEvent.VK_E, KeyEvent.CTRL_DOWN_MASK, enterStkAct, JComponent.WHEN_IN_FOCUSED_WINDOW);
        doOnPress(KeyEvent.VK_F, KeyEvent.CTRL_DOWN_MASK, fixeStkAct, JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    private void initEnStockPanel() {
        enStockList = new ListeLotsEnStockPanel(this, false) {

            @Override
            public ListeLotsEnStockPanel initTableView() {
                super.initTableView();
                getTable().setColumnVisible("Réf/C.B", false);
                getTable().setColumnVisible("Désignation", false);
                getTable().setColumnVisible("PU.Achat", false);
                getTable().setColumnVisible("PU.Vnt.Gr", false);
                getTable().setColumnVisible("PU.Vnt.Dt", false);
                getTable().setColumnVisible("Date.Alert", false);
                getTable().setColumnVisible("Actif", false);
                return this;
            }
        };
        enStockList.setMasterPanel(this, "ID_PROD");
    }

    private final Action enterStkAct = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            enStockList.insert();
            reload();
        }
    };

    private final Action fixeStkAct = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            fixeStk();
            reload();
        }
    };

    public void fixeStk() {
        if (getModelSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Aucun produit sélectionné!");
            return;
        }
        if (enStockList.getTable().getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Ce produit n'existe pas en stock!\nUtiliser la fonction 'Entré en Stock' pour entré ce produit en stock");
        } else if (enStockList.getTable().getRowCount() == 1) {
            enStockList.getTable().selectViewRow(0);
            enStockList.edit();
        } else {
            enStockList.getNavigOnlyList().showPanel(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        opersP = new javax.swing.JPanel();
        enterStkButton = new javax.swing.JButton();
        fixStkButton = new javax.swing.JButton();
        initStkButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 800));
        setLayout(new java.awt.BorderLayout());

        opersP.setPreferredSize(new java.awt.Dimension(486, 32));
        opersP.setLayout(new java.awt.GridBagLayout());

        enterStkButton.setAction(enterStkAct);
        enterStkButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enterStkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/stockIn24.png"))); // NOI18N
        enterStkButton.setText("Entré du Stock (Ctrl+E)");
        enterStkButton.setBorder(null);
        enterStkButton.setMaximumSize(new java.awt.Dimension(124, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        opersP.add(enterStkButton, gridBagConstraints);

        fixStkButton.setAction(fixeStkAct);
        fixStkButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fixStkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/fixStock24.png"))); // NOI18N
        fixStkButton.setText("Correction/Transfert du Stock (Ctrl+F)");
        fixStkButton.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        opersP.add(fixStkButton, gridBagConstraints);

        initStkButton.setAction(enterStkAct);
        initStkButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        initStkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/stockIn24.png"))); // NOI18N
        initStkButton.setText("Initialisation du Stock (Ctrl+E)");
        initStkButton.setBorder(null);
        initStkButton.setEnabled(false);
        initStkButton.setPreferredSize(new java.awt.Dimension(220, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        opersP.add(initStkButton, gridBagConstraints);

        add(opersP, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterStkButton;
    private javax.swing.JButton fixStkButton;
    private javax.swing.JButton initStkButton;
    private javax.swing.JPanel opersP;
    // End of variables declaration//GEN-END:variables
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new InventaireStockPanel(frame));
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
