/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FamillePanel.java
 *
 * Created on 17/10/2009, 10:36:54 ص
 */
package panels.crud;

import java.awt.BorderLayout;
import java.awt.Container;
import myComponents.MyJFrame;
import panels.RSTablePanel;
import dao.DepotDAO;
import entities.Depot;
import java.awt.Dimension;
import myComponents.MyJTable;
import panels.maj.MajDepotPanel;

/**
 *
 * @author alilo
 */
public class ListeDepotsPanel extends RSTablePanel<Depot, DepotDAO> {
    {
        setPreferredSize(new Dimension(550, 450));
        setMajPanel(new MajDepotPanel(this));
        setFilterShortcut("CTRL", "F");
    }
    public ListeDepotsPanel(Container owner, boolean checkable) {
        super(owner, checkable);
        //setAllowedOperations(new int[]{INSERT, EDIT, DELETE}, new boolean[]{LoginDialog.isLoginAsAdmin(), LoginDialog.isLoginAsAdmin(), LoginDialog.isLoginAsAdmin()});
    }

    @Override
    public ListeDepotsPanel initTableView() {
        getTable().setColumnVisible("ID", false);
        getTable().setColumnsPreferredWidths(new int[]{200});
        return this;
    }

    @Override
    public ListeDepotsPanel getNavigNEditList() {
        setPreferredSize(new Dimension(250, 450));
        getTable().setColumnVisible("De.Vente", false);
        getTable().setColumnVisible("De.Réserve", false);
        getTable().setColumnVisible("De.Stockage", false);
        return this;
    }
    
    public ListeDepotsPanel getDepotsDeVente(){
        setPreferredSize(new Dimension(250, 350));
        //getTable().setColumnVisible("De.Vente", false);
        getTable().setColumnVisible("De.Réserve", false);
        getTable().setColumnVisible("De.Stockage", false);
        filterList("De.Vente", "true", MyJTable.EXACT_MATCH_FILTER);
        return this;
    }

    @Override
    public DepotDAO getTableDAO() {
        return DepotDAO.getInstance();
    }

    /**
     * ***********************************************************************
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(300, 450));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new ListeDepotsPanel(frame, false).getDepotsDeVente(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
