/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FamillePanel.java
 *
 * Created on 17/10/2009, 10:36:54 ص
 */
package panels.crud;

import entities.Unite;
import java.awt.BorderLayout;
import java.awt.Container;
import myComponents.MyJFrame;
import myModels.ResultSet2TableModel;
import panels.RSTablePanel;
import dao.UniteDAO;
import java.awt.Dimension;
import panels.maj.MajUnitePanel;

/**
 *
 * @author alilo
 */
public class ListeUnitesPanel extends RSTablePanel<Unite, UniteDAO> {
    {
        setPreferredSize(new Dimension(550, 450));
        setMajPanel(new MajUnitePanel(this));
        setFilterShortcut("CTRL", "F");
    }
    public ListeUnitesPanel(Container owner, boolean checkable) {
        super(owner, checkable);
    }

    @Override
    public ListeUnitesPanel initTableView() {
        getTable().setColumnVisible("ID", false);
        getTable().setColumnsPreferredWidths(new int[]{100});
        return this;
    }

    @Override
    public UniteDAO getTableDAO() {
        return UniteDAO.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(300, 450));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new ListeUnitesPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
