/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.crud;

import entities.Famille;
import java.awt.BorderLayout;
import java.awt.Container;
import myComponents.MyJFrame;
import myModels.ResultSet2TableModel;
import panels.RSTablePanel;
import dao.FamilleDAO;
import java.awt.Dimension;
import panels.maj.MajFamillePanel;

/**
 *
 * @author alilo
 */
public class ListeFamillesPanel extends RSTablePanel<Famille, FamilleDAO> {
    {
        setPreferredSize(new Dimension(300, 400));
        setMajPanel(new MajFamillePanel(this));
        setFilterShortcut("CTRL", "F");
    }

    public ListeFamillesPanel(Container owner, boolean checkable) {
        super(owner ,checkable);
    }

    //customize the table view
    @Override
    public ListeFamillesPanel initTableView() {
        getTable().setColumnVisible("ID", false); 
        getTable().setColumnsPreferredWidths(new int[]{200});
        return this;
    }

    @Override
    public FamilleDAO getTableDAO() {
        return FamilleDAO.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(300, 600));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new ListeFamillesPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
