/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CtegoriePanel.java
 *
 * Created on 17/10/2009, 11:25:33 ص
 */
package panels.crud;

import java.awt.BorderLayout;
import java.awt.Container;
import myComponents.MyJFrame;
import myModels.ResultSet2TableModel;
import panels.RSTablePanel;
import dao.ReglementFrDAO;
import entities.ReglementFr;
import java.awt.Dimension;
import panels.maj.MajReglementFrPanel;

/**
 *
 * @author alilo
 */
public class ListeReglementsFrPanel extends RSTablePanel<ReglementFr, ReglementFrDAO> {
    {
        setPreferredSize(new Dimension(750, 450));
        setMajPanel(new MajReglementFrPanel(this));
        setFilterShortcut("CTRL", "F");
    }
    public ListeReglementsFrPanel(Container owner, boolean checkable) {
        super(owner, checkable);
    }

    @Override
    public ListeReglementsFrPanel initTableView() {
        getTable().setColumnVisible("ID", false);
        getTable().setColumnVisible("ID_FR", false);
        getTable().setColumnVisible("ID_ACH", false);
        getTable().setColumnsPreferredWidths(new int[]{40, 40, 40, 40, 40, 200});
        return this;
    }

    @Override
    public ReglementFrDAO getTableDAO() {
        return ReglementFrDAO.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(500, 450));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new ListeReglementsFrPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }
}
