/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CtegoriePanel.java
 *
 * Created on 17/10/2009, 11:25:33 ص
 */
package panels.crud;

import dao.CreditClDAO;
import java.awt.BorderLayout;
import java.awt.Container;
import myComponents.MyJFrame;
import panels.ResultSet2Table_Panel;
import entities.CreditCl;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import panels.maj.MajCreditClPanel;

/**
 *
 * @author alilo
 */
public class ListeCreditClPanel extends ResultSet2Table_Panel<CreditCl, CreditClDAO> {
    {
        setPreferredSize(new Dimension(750, 450));
        setMajPanel(new MajCreditClPanel(this));
        setFilterShortcut("CTRL", "F");
    }
    public ListeCreditClPanel(Container owner, boolean checkable) {
        super(owner, checkable);
    }

    @Override
    public ListeCreditClPanel initTableView() {
        getTable().setColumnVisible("ID", false);
        getTable().setColumnVisible("ID_CL", false);
        getTable().setColumnVisible("ID_VNT", false);
        getTable().setColumnsPreferredWidths(new int[]{40, 40, 40, 40, 40, 200});
        return this;
    }

    @Override
    public CreditClDAO getTableDAO() {
        return CreditClDAO.getInstance();
    }

    @Override
    public void edit() {
        if(getSelectedEntity() instanceof CreditCl && getSelectedEntity().getVente() != null){
            String mess = "Vous ne pouvez pas modifier ce 'Crédit'!\nCar il est issue du: " + getSelectedEntity().getVente();
            JOptionPane.showMessageDialog(this, mess, "Attention!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        super.edit();
    }
    @Override
    public void delete() {
        if(getSelectedEntity() instanceof CreditCl && getSelectedEntity().getVente() != null){
            String mess = "Vous ne pouvez pas supprimer ce 'Crédit'!\nCar il est issue du: " + getSelectedEntity().getVente();
            JOptionPane.showMessageDialog(this, mess, "Attention!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        super.delete(); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(500, 450));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new ListeCreditClPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }
}
