-- Start 10/05/2016
----------
-- Tables
----------
-- Produit
--25/05/2016;
--01/06/2016;
ALTER TABLE PRODUIT DROP PMP;
ALTER TABLE PRODUIT DROP COLUMN MARGE_DT;
ALTER TABLE PRODUIT DROP COLUMN MARGE_GR;
ALTER TABLE PRODUIT DROP COLUMN MARGE_SGR;

ALTER TABLE PRODUIT ADD COLUMN QTE DOUBLE NOT NULL DEFAULT 0;
UPDATE PRODUIT SET QTE = QTE_GLOBAL;
ALTER TABLE PRODUIT DROP QTE_GLOBAL;
ALTER TABLE PRODUIT DROP QTE_MIN;
ALTER TABLE PRODUIT DROP QTE_MAX;

ALTER TABLE PRODUIT ADD COLUMN PU_ACH DECIMAL(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE PRODUIT ADD COLUMN PU_VNT DECIMAL(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE PRODUIT ADD COLUMN CUMP DECIMAL(12,2) NOT NULL DEFAULT 0;

-- Unité
ALTER TABLE UNITE ADD COLUMN QTE DOUBLE NOT NULL DEFAULT 1;
UPDATE UNITE SET QTE = QTE_COLIS/QTE_MORCE;
ALTER TABLE UNITE DROP COLUMN QTE_COLIS;
ALTER TABLE UNITE DROP COLUMN QTE_MORCE;
---------
-- Views
---------
-- Produit
DROP VIEW V_PRODUIT;
CREATE VIEW V_PRODUIT AS
SELECT PROD.ID, PROD.ID_FAM, PROD.ID_CATEG, COD_BAR AS "Réf/C.B", PROD.DES AS "Désignation", 
       QTE_GLOBAL AS "Qte.Stock"
FROM PRODUIT PROD;
-- Unite
CREATE VIEW V_UNITE AS
SELECT ID, DES AS "Désignation", QTE AS "Quantité"
FROM UNITE;
-- Vente
DROP VIEW V_VENTE_ALL;

CREATE VIEW V_VENTE_ALL AS
SELECT VNT.ID, CL.ID AS "ID_CL", VNT.ID_USER, VNT.NUM AS "N°", VNT."DATE" AS "Date", VNT.HEURE AS "Heure", CL.NOM AS "Client", 
    VNT.TOTAL AS "Total(DA)", VNT.VALIDEE AS "Livrée?", U.LOGIN AS "Vendeur"
FROM  VENTE VNT LEFT JOIN CLIENT CL ON VNT.ID_CL = CL.ID
                INNER JOIN APP_USER U ON VNT.ID_USER = U.ID
ORDER BY VNT."DATE" DESC, VNT.HEURE DESC;
-- LACH
CREATE VIEW V_LIGNE_ACHAT AS
SELECT LACH.ID, LACH.ID_ACH, LACH.ID_PROD, PROD.COD_BAR AS "Réf/C.B", PROD.DES AS "Produit", LACH.PU_ACH AS "PU.Achat", 
        LACH.QTE AS "Qte", U.DES AS "Unité", LACH.TOTAL_LACH AS "S.Total(DA)"
FROM (LIGNE_ACH LACH INNER JOIN UNITE U ON LACH.UNITE = U.ID) INNER JOIN PRODUIT PROD ON LACH.ID_PROD = PROD.ID
ORDER BY LACH.ID;
-- LVNT
CREATE VIEW V_LIGNE_VENTE AS
SELECT LVNT.ID, LVNT.ID_VNT, S.ID_PROD, S.ID_DEPOT, LVNT.QTE_UNIT <= S.QTE AS "Dispo", 
    S.COD_BAR AS "Réf/C.B", PROD.DES AS "Produit", LVNT.PU_VNT AS "PU.Vente", 
    LVNT.QTE AS "Qte.Vendue", U.DES AS "Unité.Vnt", LVNT.TOTAL_LVNT AS "S.Total(DA)"
FROM LIGNE_VNT LVNT INNER JOIN UNITE U ON LVNT.UNITE_VNT = U.ID 
        INNER JOIN EN_STOCK S ON LVNT.ID_EN_STK = S.ID 
        INNER JOIN  PRODUIT PROD ON S.ID_PROD = PROD.ID
ORDER BY LVNT.ID;
------------
-- Triggers
------------
