/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.maj;

import java.awt.Component;
import javax.swing.JOptionPane;
import myComponents.MyJField;
import dao.DepotDAO;
import entities.Depot;
import panels.CRUDPanel;

/**
 *
 * @author alilo
 */
public class MajDepotPanel extends panels.maj.MajPanel<Depot, DepotDAO> {

    private String adr;

    /**
     * Creates new form MajFamillePanel
     * @param listPanel
     */
    public MajDepotPanel(CRUDPanel listPanel) {
        super(listPanel);
        initComponents();
        initMajPanel(fieldsPanel);
    }

    // Getters
    @Override
    public DepotDAO getTableDAO() {
        return DepotDAO.getInstance();
    }

    @Override
    public Component getDefaultFocusedComp() {
        return adrField;
    }
    
    @java.lang.Override
    public void initFields(Depot oldEntity) {
        adrField.setText(oldEntity.getAdr());
        deVntCheckBox.setSelected(oldEntity.getDeVente());
        deRsrvCheckBox.setSelected(oldEntity.getDeReserve());
        deStkCheckBox.setSelected(oldEntity.getDeStockage());
    }

    @Override
    public void clearFields() {
        adrField.setText("");
        adrField.requestFocus();
        deVntCheckBox.setSelected(false);
        deRsrvCheckBox.setSelected(false);
        deStkCheckBox.setSelected(false);
    }

    @Override
    public boolean verifyFields() {
        String adrTxt = adrField.getText().trim();
        if ((adrTxt.length() == 0)) {
            JOptionPane.showMessageDialog(this, "Entrez l'adresse du dépôt SVP!!!", "Attention...", JOptionPane.WARNING_MESSAGE);
            adrField.requestFocus();
            return false;
        }
        this.adr = adrTxt.toUpperCase();
        if (!(deVntCheckBox.isSelected() || deRsrvCheckBox.isSelected() || deStkCheckBox.isSelected())){
            JOptionPane.showMessageDialog(this, "Sélectionnez le type du dépôt SVP!!!", "Attention...", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    @Override
    public boolean save() {
        if (verifyFields()) {
            setEditedEntity(new Depot(0, adr, deVntCheckBox.isSelected(), deRsrvCheckBox.isSelected(), deStkCheckBox.isSelected(), false, false, false));
            return super.save();
        } else {
            setSaved(false);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        responsablePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        managerField = new myComponents.MyJField();
        findProdButton = new javax.swing.JButton();
        fieldsPanel = new javax.swing.JPanel();
        stkPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adrField = new MyJField();
        deVntCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        deRsrvCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        deStkCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();

        responsablePanel.setLayout(new javax.swing.BoxLayout(responsablePanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Manager:");
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 15));
        responsablePanel.add(jLabel7);

        managerField.setEditable(false);
        managerField.setBackground(new java.awt.Color(204, 204, 255));
        managerField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        responsablePanel.add(managerField);

        findProdButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/find.png"))); // NOI18N
        findProdButton.setFocusable(false);
        findProdButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        findProdButton.setMaximumSize(new java.awt.Dimension(27, 27));
        findProdButton.setMinimumSize(new java.awt.Dimension(27, 27));
        findProdButton.setPreferredSize(new java.awt.Dimension(27, 27));
        findProdButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        responsablePanel.add(findProdButton);

        fieldsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        stkPanel.setLayout(new javax.swing.BoxLayout(stkPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Adresse:");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 15));
        stkPanel.add(jLabel5);
        stkPanel.add(adrField);

        buttonGroup1.add(deVntCheckBox);
        deVntCheckBox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        deVntCheckBox.setSelected(true);
        deVntCheckBox.setText("C'est un Dépôt de Vente.");
        deVntCheckBox.setBorder(null);
        deVntCheckBox.setFocusable(false);
        deVntCheckBox.setMinimumSize(new java.awt.Dimension(82, 16));
        deVntCheckBox.setPreferredSize(new java.awt.Dimension(82, 15));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("Seules les produits dans ce dépôt seront disponible au vente.");

        buttonGroup1.add(deRsrvCheckBox);
        deRsrvCheckBox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        deRsrvCheckBox.setText("C'est un Dépôt de Réserve.");
        deRsrvCheckBox.setBorder(null);
        deRsrvCheckBox.setFocusable(false);
        deRsrvCheckBox.setMinimumSize(new java.awt.Dimension(82, 16));
        deRsrvCheckBox.setPreferredSize(new java.awt.Dimension(82, 15));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Les produits dans ce dépôt seront accessible au superviseur seulement.");

        buttonGroup1.add(deStkCheckBox);
        deStkCheckBox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        deStkCheckBox.setText("C'est un Dépôt de Stockage.");
        deStkCheckBox.setBorder(null);
        deStkCheckBox.setFocusable(false);
        deStkCheckBox.setMinimumSize(new java.awt.Dimension(82, 16));
        deStkCheckBox.setPreferredSize(new java.awt.Dimension(82, 15));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Les produits dans ce dépôt ne seront  pas disponible au vente.");

        javax.swing.GroupLayout fieldsPanelLayout = new javax.swing.GroupLayout(fieldsPanel);
        fieldsPanel.setLayout(fieldsPanelLayout);
        fieldsPanelLayout.setHorizontalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deRsrvCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deVntCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fieldsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addComponent(stkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2))
                .addComponent(deStkCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fieldsPanelLayout.setVerticalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addComponent(stkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deVntCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deRsrvCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deStkCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private myComponents.MyJField adrField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox deRsrvCheckBox;
    private javax.swing.JCheckBox deStkCheckBox;
    private javax.swing.JCheckBox deVntCheckBox;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JButton findProdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private myComponents.MyJField managerField;
    private javax.swing.JPanel responsablePanel;
    private javax.swing.JPanel stkPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MajDepotPanel(null).showNewPanel(null);
            }
        });
    }
}
