/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.maj;

import entities.Famille;
import java.awt.Component;
import javax.swing.JOptionPane;
import myComponents.IntegerJField;
import myComponents.MyJField;
import dao.FamilleDAO;
import panels.CRUDPanel;

/**
 *
 * @author alilo
 */
public class MajFamillePanel extends panels.maj.MajPanel<Famille, FamilleDAO> {

    private String des;
    private Short tva;
    private boolean services;

    /**
     * Creates new form MajFamillePanel
     * @param listPanel
     */
    public MajFamillePanel(CRUDPanel listPanel) {
        super(listPanel);
        initComponents();
        initMajPanel(fieldsPanel);
    }

    // Getters

    @Override
    public FamilleDAO getTableDAO() {
        return FamilleDAO.getInstance();
    }

    @Override
    public Component getDefaultFocusedComp() {
        return desField;
    }
    
    @java.lang.Override
    public void initFields(Famille oldEntity) {
        desField.setText(oldEntity.getDes());
        tvaField.setText(oldEntity.getTva().toString());
        servicesChB.setSelected(oldEntity.isServices());
    }

    @Override
    public void clearFields() {
        desField.requestFocus();
        desField.setText("");
        tvaField.setText("");
        servicesChB.setSelected(false);
    }

    @Override
    public boolean verifyFields() {
        String desTxt = desField.getText().trim();
        String tvaTxt = tvaField.getText().trim();
        if ((desTxt.length() == 0) || (tvaTxt.length() == 0)) {
            JOptionPane.showMessageDialog(this, "Rempli tous les champs SVP!!!", "Attention...", JOptionPane.WARNING_MESSAGE);
            if (desTxt.length() == 0) {
                desField.requestFocus();
            } else {
                tvaField.requestFocus();
            }
            return false;
        }
        this.des = desTxt.toUpperCase();
        try {
            this.tva = Short.valueOf(tvaTxt); 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caractère non autorisé!!!  La valeur TVA doit être un chifre", "Validation...", JOptionPane.WARNING_MESSAGE);
            tvaField.requestFocus();
            return false;
        }
        services = servicesChB.isSelected();
        return true;
    }

    @Override
    public boolean save() {
        if (verifyFields()) {
            setEditedEntity(new Famille(0, des, tva, services));
            return super.save();
        } else {
            setSaved(false);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        desField = new MyJField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tvaField = new IntegerJField();
        jLabel3 = new javax.swing.JLabel();
        servicesChB = new javax.swing.JCheckBox();

        fieldsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Désignation:");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 15));
        jPanel2.add(jLabel5);

        desField.setPrefsLangKey("MajFam_Des_Lang");
        jPanel2.add(desField);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Taux de TVA:");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 15));
        jPanel3.add(jLabel4);

        tvaField.setText("0");
        tvaField.setPreferredSize(new java.awt.Dimension(50, 27));
        jPanel3.add(tvaField);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText(" %  ");
        jPanel3.add(jLabel3);

        servicesChB.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        servicesChB.setText("C'est une famille des services");
        servicesChB.setBorder(null);
        jPanel3.add(servicesChB);

        javax.swing.GroupLayout fieldsPanelLayout = new javax.swing.GroupLayout(fieldsPanel);
        fieldsPanel.setLayout(fieldsPanelLayout);
        fieldsPanelLayout.setHorizontalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fieldsPanelLayout.setVerticalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private myComponents.MyJField desField;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox servicesChB;
    private myComponents.MyJField tvaField;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MajFamillePanel(null).showNewPanel(null);
            }
        });
    }
}
