/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CtegoriePanel.java
 *
 * Created on 17/10/2009, 11:25:33 ص
 */
package panels.details;

import dao.LigneAchatDAO;
import entities.EntityClass;
import java.awt.BorderLayout;
import java.awt.Container;
import java.math.BigDecimal;
import java.sql.ResultSet;
import myComponents.MyJFrame;
import panels.ResultSet2Table_Panel;
import panels.views.MontantPanel;
import entities.Achat;
import entities.LigneAch;
import java.awt.Color;
import java.awt.Dimension;
import panels.Notification;
import panels.maj.MajLigneAchPanel;

/**
 *
 * @author alilo
 */
public class DetailsAchatPanel extends ResultSet2Table_Panel<LigneAch, LigneAchatDAO> {

    {
        setPreferredSize(new Dimension(600, 400));
        setMajPanel(new MajLigneAchPanel(this));
        setFilterShortcut("CTRL", "F");
    }

    private Achat masterAchat;
    private BigDecimal total;
    private final MontantPanel totalPanel = new MontantPanel();

    public DetailsAchatPanel(Container owner, boolean checkable) {
        super(owner, checkable);
        
        statusPanel.add(totalPanel);
    }

    @Override
    public DetailsAchatPanel initTableView() {
        getTable().setColumnVisible("ID", false);
        getTable().setColumnVisible("ID_ACH", false);
        getTable().setColumnVisible("ID_PROD", false);
        getTable().setColumnsPreferredWidths(new int[]{100, 160});
        return this;
    }
    
    @Override
    public LigneAchatDAO getTableDAO() {
        return LigneAchatDAO.getInstance();
    }

    @Override
    public ResultSet getResultSet() {
        if (masterAchat != null) {
            return getTableDAO().getDetailsAchat(masterAchat);
        } else {
            return super.getResultSet();
        }
    }

    @Override
    public void doOnTableModelChanged() {
        super.doOnTableModelChanged();
        showTotal();
    }

    private final Notification notifStatus = Notification.createNotification(3, "Status: ", "?", java.awt.Color.BLACK, "Square721 BT", 16, true, true);
    private final Color valideeColor = new Color(0, 204, 0);

    /**
     * Set the master 'Achat' of 'LigneAchat' list.\n the list will filtered to
     * show only the sale lines associated with this 'Achat'.
     *
     * @param achat the master sale.
     */
    public void setMasterAchat(Achat achat) {
        masterAchat = achat;
        reload();
        setAllowedOperation(INSERT, !masterAchat.isValide());
        setAllowedOperation(EDIT, !masterAchat.isValide());
        setAllowedOperation(DELETE, !masterAchat.isValide());
        if (masterAchat.getId() >= 0) {
            if (masterAchat.isValide()) {
                notifStatus.setMess("Validée!");
                notifStatus.setColor(valideeColor);
                addNotification(notifStatus, false);
            } else {
                notifStatus.setMess("Non Validée!");
                notifStatus.setColor(Color.RED);
                addNotification(notifStatus, false);
            }
        }
    }

    @Override
    public void setMasterEntity(EntityClass masterEntity) {
        super.setMasterEntity(masterEntity);
        if (masterEntity instanceof Achat) {
            setMasterAchat((Achat) masterEntity);
        }
    }

    public Achat getMasterAchat() {
        return masterAchat;
    }

    public final void showTotal() {
        if (masterAchat != null) {
            total = getMasterAchat().getTotal();
            totalPanel.setTitleString("GT:");
            totalPanel.setMontant(total);
        }
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFocusable(false);
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                //ArticleDAO.getInstance().setGetAllParam(0);
                frame.getContentPane().add(new DetailsAchatPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
