/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.crud;

import java.awt.BorderLayout;
import java.awt.Container;
import myComponents.MyJFrame;
import panels.RSTablePanel;
import dao.UGroupDAO;
import entities.UserGp;
import java.awt.Dimension;
import panels.maj.MajGroupePanel;

/**
 *
 * @author alilo
 */
public class ListeGroupsPanel extends RSTablePanel<UserGp, UGroupDAO> {
    {
        setPreferredSize(new Dimension(550, 450));
        setMajPanel(new MajGroupePanel(this));
        setFilterShortcut("CTRL", "F");
    }
    public ListeGroupsPanel(Container owner, boolean checkable) {
        super(owner ,checkable);
        setAllowedOperations(new int[]{INSERT, EDIT, DELETE}, new boolean[]{false, false, false});
    }

    //customize the table view
    @Override
    public ListeGroupsPanel initTableView() {
        getTable().setColumnVisible("ID", false); 
        return this;
    }

    @Override
    public UGroupDAO getTableDAO() {
        return UGroupDAO.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new ListeGroupsPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
