/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.crud;

import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.ResultSet;
import myComponents.MyJFrame;
import dao.VenteDAO;

/**
 *
 * @author alilo
 */
public class ListeVentesClientPanel extends ListeVentesPanel {

    /**
     * Creates new form ListeVentesClient
     * @param owner
     * @param checkable
     */
    public ListeVentesClientPanel(Container owner, boolean checkable) {
        super(owner, checkable);
    }

    @Override
    public ResultSet getResultSet() {
        return VenteDAO.getInstance().getVentesCl();
    }

    @Override
    public ListeVentesPanel initTableView() {
        getTable().setColumnVisible("ID_VNT_CL", false);
        getTable().setColumnVisible("ID_CL", false);
        super.initTableView();
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        MyJFrame frame = new MyJFrame();
        //frame.setExtendedState(Frame.MAXIMIZED_BOTH);
        frame.setTitle("Gestion des Ventes");
        frame.getContentPane().add(new ListeVentesClientPanel(frame, false).initTableView(), BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
}
