/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.crud;

import dialogs.LoginDialog;
import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import myComponents.MyJFrame;
import panels.RSTablePanel;
import dao.UserDAO;
import entities.AppUser;
import java.awt.Dimension;
import panels.maj.MajUtilisateurPanel;

/**
 *
 * @author alilo
 */
public class ListeUtilisateursPanel extends RSTablePanel<AppUser, UserDAO> {

    {
        setPreferredSize(new Dimension(550, 450));
        setMajPanel(new MajUtilisateurPanel(this));
        setFilterShortcut("CTRL", "F");
    }

    public ListeUtilisateursPanel(Container owner, boolean checkable) {
        super(owner, checkable);
        setAllowedOperation(READ, LoginDialog.isLoginAsAdmin());
    }

    //customize the table view
    @Override
    public ListeUtilisateursPanel initTableView() {
        getTable().setColumnVisible("ID", false);
        return this;
    }

    @Override
    public UserDAO getTableDAO() {
        return UserDAO.getInstance();
    }

    @Override
    public void delete() {
        if (getSelectedEntity().isAdmin() && getTableDAO().isLastAdmin()) {
            String mess = "Vous ne pouvez pas supprimer le superviseur de l'application!!!";
            JOptionPane.showMessageDialog(this, mess, "Attention...", JOptionPane.ERROR_MESSAGE);
            return;
        }
        super.delete();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new ListeUtilisateursPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
