DELETE FROM ACHAT;
ALTER TABLE ACHAT ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE LIGNE_ACH ALTER COLUMN ID RESTART WITH 1;

DELETE FROM REGLEMENT_FR;
ALTER TABLE REGLEMENT_FR ALTER COLUMN ID RESTART WITH 1;

DELETE FROM CREDIT_FR;
ALTER TABLE CREDIT_FR ALTER COLUMN ID RESTART WITH 1;

DELETE FROM FOURNISSEUR;
ALTER TABLE FOURNISSEUR ALTER COLUMN ID RESTART WITH 1;

DELETE FROM VENTE;
ALTER TABLE VENTE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE LIGNE_VNT ALTER COLUMN ID RESTART WITH 1;

DELETE FROM CREDIT_CL;
ALTER TABLE CREDIT_CL ALTER COLUMN ID RESTART WITH 1;

DELETE FROM REGLEMENT_CL;
ALTER TABLE REGLEMENT_CL ALTER COLUMN ID RESTART WITH 1;

DELETE FROM CLIENT;
ALTER TABLE CLIENT ALTER COLUMN ID RESTART WITH 1;

DELETE FROM EN_STOCK;
ALTER TABLE EN_STOCK ALTER COLUMN ID RESTART WITH 1;

DELETE FROM  PRODUIT;
ALTER TABLE PRODUIT ALTER COLUMN ID RESTART WITH 1;
DELETE FROM CATEGORIE;
ALTER TABLE CATEGORIE ALTER COLUMN ID RESTART WITH 1;
DELETE FROM FAMILLE;
ALTER TABLE FAMILLE ALTER COLUMN ID RESTART WITH 1;

DELETE FROM APP_USER;
INSERT INTO APP_USER (LOGIN, PW, ID_GROUP) VALUES ('ADMIN', '123', 1);



