/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.masterDetails;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import myComponents.MyJFrame;
import panels.ResultSet2Table_Panel;
import dao.LigneVenteDAO;
import entities.EntityClass;
import entities.LigneVnt;
import entities.Vente;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.util.Date;
import tools.DateTools;

/**
 *
 * @author alilo
 */
public class JournalVentesPanel extends ResultSet2Table_Panel<LigneVnt, LigneVenteDAO> {

    {
        setPreferredSize(new Dimension(800, 550));
        setAllowedOperation(READ, true);
        setAllowedOperation(INSERT, false);
        setAllowedOperation(EDIT, false);
        setAllowedOperation(DELETE, false);
        setFilterShortcut("CTRL", "F");
    }
    private Vente masterVnt;
    private Date beginDate , endDate, today = new Date();

    public JournalVentesPanel(Container owner, boolean checkable) {
        super(owner, checkable);
        initComponents();
        add(mainPanel, BorderLayout.CENTER);
        totalVntsP.setMontant(calculateTotal());
        statusPanel.add(totalVntsP);
    }

    @Override
    public JournalVentesPanel initTableView() {
        getTable().setColumnVisible("ID", false);
        getTable().setColumnVisible("ID_VNT", false);
        getTable().setColumnVisible("ID_PROD", false);
        getTable().setColumnVisible("ID_DEPOT", false);
        getTable().setColumnVisible("ID_USER", false);
        getTable().setColumnsPreferredWidths(new int[]{80, 120});
        //getNavigOnlyList();
        return this;
    }

    @Override
    public LigneVenteDAO getTableDAO() {
        return LigneVenteDAO.getInstance();
    }

    @Override
    public ResultSet getResultSet() {
        if(beginDate == null){
            beginDate = DateTools.TODAY;
        }
        if(endDate == null){
            endDate = DateTools.TODAY;
        }
        return getTableDAO().getJournalVentes(beginDate, endDate);
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Override
    public void setMasterEntity(EntityClass masterEntity) {
        super.setMasterEntity(masterEntity);
        if (masterEntity instanceof Vente) {
            setMasterVente((Vente) masterEntity);
        }else{
            setMasterVente(null);
        }
    }

    public void setMasterVente(Vente vnt) {
        this.masterVnt = vnt;
        reload();
    }
    
    @Override
    public void doOnTableModelChanged() {
        super.doOnTableModelChanged();
        if (totalVntsP != null) {
            totalVntsP.setMontant(calculateTotal());
        }
    }

    @Override
    public void doOnTableRowSortChanged() {
        super.doOnTableRowSortChanged();
        if (totalVntsP != null) {
            totalVntsP.setMontant(calculateTotal());
        }
    }
    
    public final BigDecimal calculateTotal() {
        BigDecimal total = new BigDecimal(0);
        for (int i = 0; i < getTable().getRowCount(); i++) {
            BigDecimal totalRow = (BigDecimal) getTable().getValueAt(i, "Total.Vente");
            total = total.add(totalRow);
        }
        return total;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalVntsP = new panels.views.MontantPanel();

        totalVntsP.setMontantFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        totalVntsP.setTitleFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        totalVntsP.setTitleString("Total.Ventes:");

        setPreferredSize(new java.awt.Dimension(250, 500));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panels.views.MontantPanel totalVntsP;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.getContentPane().add(new JournalVentesPanel(frame, false).initTableView(), BorderLayout.CENTER);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
