/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import appLogic.CurrencyConverter;
import dao.CompanyDAO;
import panels.SettingsPanel;
import panels.maj.MajCompanyPanel;
import printing.PrintingTools;
import printing.VentePrinting;


/**
 *
 * @author alilo
 */
public class MainSettingsPanel extends SettingsPanel {
    private static MainSettingsPanel instance;
    private MajCompanyPanel companyPanel = new MajCompanyPanel(null);
    /**
     * Creates new form SettingsPanel
     */
    public MainSettingsPanel() {
        super(null);
        initComponents();
        initSettingsPanel(settingsTabbedPane);
    }
    
    @Override
    public void loadSettings(){
        // Commercial Tab
        if(CurrencyConverter.getCurrencyUnit().equals(CurrencyConverter.CENTIMES)){
            centRadioBox.setSelected(true);
        }else{
            dinareRadioBox.setSelected(true);
        }
    }
    
    @Override
    public boolean saveSettings(){
        // Saving Commercial Settings
        if(centRadioBox.isSelected()){
            CurrencyConverter.setCurrencyUnit(CurrencyConverter.CENTIMES);
        }else{
            CurrencyConverter.setCurrencyUnit(CurrencyConverter.DINARES);
        }
        return true;
    }
    
    public static void open(){
        if(instance == null){
            instance = new MainSettingsPanel();
        }
        instance.showSettings();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        facturLangRadioGroup = new javax.swing.ButtonGroup();
        settingsTabbedPane = new javax.swing.JTabbedPane();
        generalSett = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lfCBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        commercSett = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        centRadioBox = new javax.swing.JRadioButton();
        dinareRadioBox = new javax.swing.JRadioButton();
        printSett = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bLArRadioB = new javax.swing.JRadioButton();
        blFrRadioB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        centRadioBox2 = new javax.swing.JRadioButton();
        dinareRadioBox2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        bLA4RadioB = new javax.swing.JRadioButton();
        bLA5RadioB = new javax.swing.JRadioButton();
        bLA6RadioB = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        qteCalcRadioB = new javax.swing.JRadioButton();
        qteXColisRadioB = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        colisDesRadioB = new javax.swing.JRadioButton();
        colisQteRadioB = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        centRadioBox6 = new javax.swing.JRadioButton();
        dinareRadioBox8 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        BLLangRadioGroup = new javax.swing.ButtonGroup();
        BLFormatRadioGrp = new javax.swing.ButtonGroup();
        qteAsRadioGrp = new javax.swing.ButtonGroup();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Thème:");

        lfCBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lfCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Système", "AcrylLookAndFeel", "AeroLookAndFeel", "AluminiumLookAndFeel", "BernsteinLookAndFeel", "FastLookAndFeel", "HiFiLookAndFeel", "LunaLookAndFeel", "McWinLookAndFeel", "MintLookAndFeel", "NoireLookAndFeel", "SmartLookAndFeel" }));
        lfCBox.setEnabled(false);
        lfCBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lfCBoxItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Langue:");
        jLabel1.setEnabled(false);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arabe", "Français", "Anglais" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.setEnabled(false);

        javax.swing.GroupLayout generalSettLayout = new javax.swing.GroupLayout(generalSett);
        generalSett.setLayout(generalSettLayout);
        generalSettLayout.setHorizontalGroup(
            generalSettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalSettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(generalSettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lfCBox, 0, 282, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        generalSettLayout.setVerticalGroup(
            generalSettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalSettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalSettLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(generalSettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lfCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("Général", new javax.swing.ImageIcon(getClass().getResource("/res/icons/tajer16.png")), generalSett); // NOI18N

        commercSett.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5));
        commercSett.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Manipuler les monétaires:");
        jLabel3.setPreferredSize(new java.awt.Dimension(175, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        commercSett.add(jLabel3, gridBagConstraints);

        facturLangRadioGroup.add(centRadioBox);
        centRadioBox.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        centRadioBox.setText("Centimes");
        centRadioBox.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.3;
        commercSett.add(centRadioBox, gridBagConstraints);

        facturLangRadioGroup.add(dinareRadioBox);
        dinareRadioBox.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        dinareRadioBox.setText("DA");
        dinareRadioBox.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.3;
        commercSett.add(dinareRadioBox, gridBagConstraints);

        settingsTabbedPane.addTab("Commercial", new javax.swing.ImageIcon(getClass().getResource("/res/icons/dollar16.png")), commercSett); // NOI18N

        printSett.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 5));
        java.awt.GridBagLayout printSettLayout = new java.awt.GridBagLayout();
        printSettLayout.columnWidths = new int[] {0, 2, 0, 2, 0, 2, 0};
        printSettLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        printSett.setLayout(printSettLayout);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Langue du Bon de Livraison:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jLabel4, gridBagConstraints);

        BLLangRadioGroup.add(bLArRadioB);
        bLArRadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        bLArRadioB.setText("Arabe");
        bLArRadioB.setFocusable(false);
        bLArRadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLArRadioBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(bLArRadioB, gridBagConstraints);

        BLLangRadioGroup.add(blFrRadioB);
        blFrRadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        blFrRadioB.setText("Français");
        blFrRadioB.setFocusable(false);
        blFrRadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blFrRadioBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(blFrRadioB, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("En-Tête de la Facture:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jLabel5, gridBagConstraints);

        centRadioBox2.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        centRadioBox2.setText("Arabe");
        centRadioBox2.setEnabled(false);
        centRadioBox2.setFocusable(false);
        centRadioBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centRadioBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(centRadioBox2, gridBagConstraints);

        dinareRadioBox2.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        dinareRadioBox2.setSelected(true);
        dinareRadioBox2.setText("Français");
        dinareRadioBox2.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(dinareRadioBox2, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Format du Bon de Livraison:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jLabel6, gridBagConstraints);

        BLFormatRadioGrp.add(bLA4RadioB);
        bLA4RadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        bLA4RadioB.setText("A4");
        bLA4RadioB.setFocusable(false);
        bLA4RadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLA4RadioBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(bLA4RadioB, gridBagConstraints);

        BLFormatRadioGrp.add(bLA5RadioB);
        bLA5RadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        bLA5RadioB.setText("A5");
        bLA5RadioB.setEnabled(false);
        bLA5RadioB.setFocusable(false);
        bLA5RadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLA5RadioBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(bLA5RadioB, gridBagConstraints);

        BLFormatRadioGrp.add(bLA6RadioB);
        bLA6RadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        bLA6RadioB.setText("A6");
        bLA6RadioB.setFocusable(false);
        bLA6RadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLA6RadioBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        printSett.add(bLA6RadioB, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Afficher les quantitées comme:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jLabel7, gridBagConstraints);

        qteAsRadioGrp.add(qteCalcRadioB);
        qteCalcRadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        qteCalcRadioB.setText("Qte Simple");
        qteCalcRadioB.setFocusable(false);
        qteCalcRadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qteCalcRadioBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(qteCalcRadioB, gridBagConstraints);

        qteAsRadioGrp.add(qteXColisRadioB);
        qteXColisRadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        qteXColisRadioB.setText("Qte X Colis");
        qteXColisRadioB.setFocusable(false);
        qteXColisRadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qteXColisRadioBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(qteXColisRadioB, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Afficher le colisage comme:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jLabel8, gridBagConstraints);

        colisDesRadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        colisDesRadioB.setText("Désignation");
        colisDesRadioB.setEnabled(false);
        colisDesRadioB.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(colisDesRadioB, gridBagConstraints);

        colisQteRadioB.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        colisQteRadioB.setText("Qte par Colis");
        colisQteRadioB.setEnabled(false);
        colisQteRadioB.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(colisQteRadioB, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Afficher le Soldes & Règlement:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jLabel9, gridBagConstraints);

        centRadioBox6.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        centRadioBox6.setText("Oui");
        centRadioBox6.setEnabled(false);
        centRadioBox6.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(centRadioBox6, gridBagConstraints);

        dinareRadioBox8.setFont(new java.awt.Font("Square721 BT", 1, 13)); // NOI18N
        dinareRadioBox8.setText("Non");
        dinareRadioBox8.setEnabled(false);
        dinareRadioBox8.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(dinareRadioBox8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jSeparator1, gridBagConstraints);

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jButton1, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Langue du Facture:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printSett.add(jLabel10, gridBagConstraints);

        settingsTabbedPane.addTab("Impression", new javax.swing.ImageIcon(getClass().getResource("/res/actions/print16.png")), printSett); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lfCBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lfCBoxItemStateChanged
       
    }//GEN-LAST:event_lfCBoxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        companyPanel.showEditPanel(CompanyDAO.getInstance().getObjectByID(1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void centRadioBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centRadioBox2ActionPerformed
        
    }//GEN-LAST:event_centRadioBox2ActionPerformed

    private void bLArRadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLArRadioBActionPerformed
        VentePrinting.getInstance(VentePrinting.BON_LIVR).setLang(PrintingTools.ARABIC);
    }//GEN-LAST:event_bLArRadioBActionPerformed

    private void blFrRadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blFrRadioBActionPerformed
        VentePrinting.getInstance(VentePrinting.BON_LIVR).setLang(PrintingTools.FRENCH);
    }//GEN-LAST:event_blFrRadioBActionPerformed

    private void bLA4RadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLA4RadioBActionPerformed
        VentePrinting.getInstance(VentePrinting.BON_LIVR).setFormat(PrintingTools.A4);
    }//GEN-LAST:event_bLA4RadioBActionPerformed

    private void bLA5RadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLA5RadioBActionPerformed
       VentePrinting.getInstance(VentePrinting.BON_LIVR).setFormat(PrintingTools.A5);
    }//GEN-LAST:event_bLA5RadioBActionPerformed

    private void bLA6RadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLA6RadioBActionPerformed
        VentePrinting.getInstance(VentePrinting.BON_LIVR).setFormat(PrintingTools.A6);
    }//GEN-LAST:event_bLA6RadioBActionPerformed

    private void qteCalcRadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qteCalcRadioBActionPerformed
        VentePrinting.getInstance(VentePrinting.BON_LIVR).setPrintQteAs(VentePrinting.NO_COLIS);
    }//GEN-LAST:event_qteCalcRadioBActionPerformed

    private void qteXColisRadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qteXColisRadioBActionPerformed
        VentePrinting.getInstance(VentePrinting.BON_LIVR).setPrintQteAs(VentePrinting.BY_COLIS);
    }//GEN-LAST:event_qteXColisRadioBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BLFormatRadioGrp;
    private javax.swing.ButtonGroup BLLangRadioGroup;
    private javax.swing.JRadioButton bLA4RadioB;
    private javax.swing.JRadioButton bLA5RadioB;
    private javax.swing.JRadioButton bLA6RadioB;
    private javax.swing.JRadioButton bLArRadioB;
    private javax.swing.JRadioButton blFrRadioB;
    private javax.swing.JRadioButton centRadioBox;
    private javax.swing.JRadioButton centRadioBox2;
    private javax.swing.JRadioButton centRadioBox6;
    private javax.swing.JRadioButton colisDesRadioB;
    private javax.swing.JRadioButton colisQteRadioB;
    private javax.swing.JPanel commercSett;
    private javax.swing.JRadioButton dinareRadioBox;
    private javax.swing.JRadioButton dinareRadioBox2;
    private javax.swing.JRadioButton dinareRadioBox8;
    private javax.swing.ButtonGroup facturLangRadioGroup;
    private javax.swing.JPanel generalSett;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox lfCBox;
    private javax.swing.JPanel printSett;
    private javax.swing.ButtonGroup qteAsRadioGrp;
    private javax.swing.JRadioButton qteCalcRadioB;
    private javax.swing.JRadioButton qteXColisRadioB;
    private javax.swing.JTabbedPane settingsTabbedPane;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
        MainSettingsPanel.open();
    }
}
