-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2013-10-07 23:37:50.139
-- Source database is: db_am
-- Connection URL is: jdbc:derby://localhost:1527/db_am
-- Specified schema is: alilo
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for schemas
-- ----------------------------------------------

CREATE SCHEMA "ALILO";

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "ALILO"."EMBALLAGE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DES" VARCHAR(25) NOT NULL, "QTE_LOT" INTEGER NOT NULL DEFAULT 1, "QTE_LOT_DECIMAL" INTEGER NOT NULL DEFAULT 1, "ID_UNITE" INTEGER NOT NULL);

CREATE TABLE "ALILO"."UNITE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DES" VARCHAR(20) NOT NULL);

CREATE TABLE "ALILO"."ACHAT_FOUR" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ID_FOUR" INTEGER NOT NULL, "ID_ACHAT" INTEGER NOT NULL, "TOTAL_VERSS" DECIMAL(10,2) NOT NULL DEFAULT 0);

CREATE TABLE "ALILO"."LIGNE_ACHAT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ID_ACHAT" INTEGER NOT NULL, "ID_PROD" INTEGER NOT NULL, "PU_ACHAT" DECIMAL(10,2) NOT NULL DEFAULT 0, "QTE_ACHETE" INTEGER NOT NULL, "UNITE_ACHAT" INTEGER NOT NULL, "TOTAL_LACH" DECIMAL(10,2) NOT NULL DEFAULT 0);

CREATE TABLE "ALILO"."REGLEMENT_CL" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DATE_VERS" DATE DEFAULT CURRENT_DATE, "MONTANT" DECIMAL(10,2) NOT NULL DEFAULT 0, "TYPE_PAY" VARCHAR(20), "ID_VNT_CL" INTEGER);

CREATE TABLE "ALILO"."CATEGORIE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DES" VARCHAR(50) NOT NULL, "ID_FAM" INTEGER NOT NULL);

CREATE TABLE "ALILO"."PRODUIT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "REFER" VARCHAR(30) NOT NULL, "DES" VARCHAR(50) NOT NULL, "S_STK" INTEGER NOT NULL DEFAULT 0, "MARGE_GR" DECIMAL(7,2) NOT NULL DEFAULT 1, "TYPE_MARG_GR" CHAR(1) NOT NULL DEFAULT '%', "MARGE_DT" DECIMAL(7,2) NOT NULL DEFAULT 1, "TYPE_MARG_DT" CHAR(1) NOT NULL DEFAULT '%', "ID_CATEG" INTEGER NOT NULL, "ID_STOCK" INTEGER NOT NULL, "ID_UNIT_VENTE" INTEGER NOT NULL, "ID_UNIT_SEUIL" INTEGER NOT NULL);

CREATE TABLE "ALILO"."VENTE_CL" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ID_CL" INTEGER NOT NULL, "ID_VNT" INTEGER NOT NULL, "TOTAL_VERSS" DECIMAL(10,2) NOT NULL DEFAULT 0);

CREATE TABLE "ALILO"."LIGNE_VNT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ID_VNT" INTEGER NOT NULL, "ID_ART" INTEGER NOT NULL, "PU_VNT" DECIMAL(10,2) NOT NULL DEFAULT 0, "QTE_VENDU" INTEGER NOT NULL, "UNITE_VNT" INTEGER NOT NULL, "VALIDEE" CHAR(1) NOT NULL DEFAULT 'N', "QTE_VEND_COLIS" INTEGER NOT NULL DEFAULT 0, "QTE_VEND_VRAC" INTEGER NOT NULL DEFAULT 0, "TOTAL_LVNT" DECIMAL(10,2) NOT NULL DEFAULT 0);

CREATE TABLE "ALILO"."QUANTIFIER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ID_PROD" INTEGER NOT NULL, "ID_EMB" INTEGER NOT NULL);

CREATE TABLE "ALILO"."CLIENT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(40) NOT NULL, "ADR" VARCHAR(50), "TEL" CHAR(10), "NUM_RC" CHAR(10) DEFAULT '##########', "NUM_FISC" CHAR(15) DEFAULT '###############', "NUM_ART" CHAR(11) DEFAULT '###########', "APP_TVA" CHAR(1) NOT NULL DEFAULT 'Y', "CREDIT" DECIMAL(10,2) NOT NULL DEFAULT 0, "CREDIT_INITIAL" DECIMAL(10,2) NOT NULL DEFAULT 0);

CREATE TABLE "ALILO"."ROLE_UTILIS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DES" VARCHAR(50) NOT NULL);

CREATE TABLE "ALILO"."FOURNISSEUR" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(40) NOT NULL, "ADR" VARCHAR(50), "TEL" CHAR(10), "NUM_RC" CHAR(10) DEFAULT '##########', "NUM_FISC" CHAR(15) DEFAULT '###############', "NUM_ART" CHAR(11) DEFAULT '###########', "CREDIT" DECIMAL(10,2) NOT NULL DEFAULT 0);

CREATE TABLE "ALILO"."UTILISATEUR" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "LOGIN" VARCHAR(25) NOT NULL, "PW" VARCHAR(25) NOT NULL, "ID_ROLE" INTEGER NOT NULL);

CREATE TABLE "ALILO"."REGLEMENT_FOUR" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DATE_VERS" DATE DEFAULT CURRENT_DATE, "MONTANT" DECIMAL(10,2) NOT NULL DEFAULT 0, "TYPE_PAY" VARCHAR(20), "ID_ACH_FR" INTEGER NOT NULL);

CREATE TABLE "ALILO"."ACHAT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NUM" INTEGER NOT NULL, "DATE" DATE DEFAULT CURRENT_DATE, "TOTAL" DECIMAL(10,2) NOT NULL DEFAULT 0, "VALIDE" CHAR(1) NOT NULL DEFAULT 'N');

CREATE TABLE "ALILO"."STOCK" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ADR" VARCHAR(50) NOT NULL);

CREATE TABLE "ALILO"."ARTICLE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "PU_VENTE_GR" DECIMAL(10,2) DEFAULT 0, "PU_VENTE_DT" DECIMAL(10,2) DEFAULT 0, "QTE_STK_REEL" INTEGER NOT NULL DEFAULT 0, "QTE_EN_VRAC" INTEGER NOT NULL DEFAULT 0, "ID_L_ACHAT" INTEGER NOT NULL, "ACTIVE" CHAR(1) NOT NULL DEFAULT 'N');

CREATE TABLE "ALILO"."STOCKER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ID_PROD" INTEGER NOT NULL, "ID_STOCK" INTEGER NOT NULL);

CREATE TABLE "ALILO"."FAMILLE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DES" VARCHAR(50) NOT NULL, "TVA" SMALLINT DEFAULT 0);

CREATE TABLE "ALILO"."VENTE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NUM" INTEGER NOT NULL, "DATE" DATE DEFAULT CURRENT_DATE, "HEURE" TIME NOT NULL DEFAULT CURRENT_TIME, "TYPE_VNT" VARCHAR(6) NOT NULL, "VALIDE" CHAR(1) NOT NULL DEFAULT 'N', "TOTAL" DECIMAL(10,2) NOT NULL DEFAULT 0);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "ALILO"."QUANTIFIER" ADD CONSTRAINT "QUANTIF_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."REGLEMENT_FOUR" ADD CONSTRAINT "VERS_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."LIGNE_VNT" ADD CONSTRAINT "LIGNEVNT_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."STOCKER" ADD CONSTRAINT "STOCKER_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."ROLE_UTILIS" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."ACHAT_FOUR" ADD CONSTRAINT "ACH_FOUR_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."UTILISATEUR" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."UTILISATEUR" ADD CONSTRAINT "UNIQE_LOGIN" UNIQUE ("LOGIN");

ALTER TABLE "ALILO"."ACHAT" ADD CONSTRAINT "ACHAT_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."CATEGORIE" ADD CONSTRAINT "CAT_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."FAMILLE" ADD CONSTRAINT "FAM_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."VENTE_CL" ADD CONSTRAINT "VNTCL_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."STOCK" ADD CONSTRAINT "SQL130927175717330" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."UNITE" ADD CONSTRAINT "SQL130927171132720" UNIQUE ("DES");

ALTER TABLE "ALILO"."UNITE" ADD CONSTRAINT "UNIT_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."VENTE" ADD CONSTRAINT "VNT_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."FOURNISSEUR" ADD CONSTRAINT "FOURN_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."PRODUIT" ADD CONSTRAINT "PROD_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."PRODUIT" ADD CONSTRAINT "REFER_UNIQ" UNIQUE ("REFER");

ALTER TABLE "ALILO"."EMBALLAGE" ADD CONSTRAINT "PACK_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."LIGNE_ACHAT" ADD CONSTRAINT "L_ACHAT_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."ARTICLE" ADD CONSTRAINT "ART_PK" PRIMARY KEY ("ID");

ALTER TABLE "ALILO"."REGLEMENT_CL" ADD CONSTRAINT "VRS_CL_PK" PRIMARY KEY ("ID");

-- FOREIGN
ALTER TABLE "ALILO"."QUANTIFIER" ADD CONSTRAINT "QUANTIF_PROD_FK" FOREIGN KEY ("ID_PROD") REFERENCES "ALILO"."PRODUIT" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."QUANTIFIER" ADD CONSTRAINT "QUANTIF_EMB_FK" FOREIGN KEY ("ID_EMB") REFERENCES "ALILO"."EMBALLAGE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."REGLEMENT_FOUR" ADD CONSTRAINT "VERS_FR_ACH_FK" FOREIGN KEY ("ID_ACH_FR") REFERENCES "ALILO"."ACHAT_FOUR" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."LIGNE_VNT" ADD CONSTRAINT "LIGNEVNT_VNT_FK" FOREIGN KEY ("ID_VNT") REFERENCES "ALILO"."VENTE" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."LIGNE_VNT" ADD CONSTRAINT "LIGNEVNT_ART_FK" FOREIGN KEY ("ID_ART") REFERENCES "ALILO"."ARTICLE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."LIGNE_VNT" ADD CONSTRAINT "LIGNEVNT_EMB_FK" FOREIGN KEY ("UNITE_VNT") REFERENCES "ALILO"."EMBALLAGE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."STOCKER" ADD CONSTRAINT "STOCKER_PROD_FK" FOREIGN KEY ("ID_PROD") REFERENCES "ALILO"."PRODUIT" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."STOCKER" ADD CONSTRAINT "STOCKER_STK_FK" FOREIGN KEY ("ID_STOCK") REFERENCES "ALILO"."STOCK" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."ACHAT_FOUR" ADD CONSTRAINT "ACH_FOUR_FOUR_FK" FOREIGN KEY ("ID_FOUR") REFERENCES "ALILO"."FOURNISSEUR" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."ACHAT_FOUR" ADD CONSTRAINT "ACH_FOUR_ACH_FK" FOREIGN KEY ("ID_ACHAT") REFERENCES "ALILO"."ACHAT" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."UTILISATEUR" ADD CONSTRAINT "USER_ROLE_FK" FOREIGN KEY ("ID_ROLE") REFERENCES "ALILO"."ROLE_UTILIS" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."CATEGORIE" ADD CONSTRAINT "CAT_FAM_FK" FOREIGN KEY ("ID_FAM") REFERENCES "ALILO"."FAMILLE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."VENTE_CL" ADD CONSTRAINT "VNTCL_CL_FK" FOREIGN KEY ("ID_CL") REFERENCES "ALILO"."CLIENT" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."VENTE_CL" ADD CONSTRAINT "VNTCL_VNT_FK" FOREIGN KEY ("ID_VNT") REFERENCES "ALILO"."VENTE" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."PRODUIT" ADD CONSTRAINT "PROD_CAT_FK" FOREIGN KEY ("ID_CATEG") REFERENCES "ALILO"."CATEGORIE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."PRODUIT" ADD CONSTRAINT "PROD_STK_FK" FOREIGN KEY ("ID_STOCK") REFERENCES "ALILO"."STOCK" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."PRODUIT" ADD CONSTRAINT "PROD_UNIT_FK" FOREIGN KEY ("ID_UNIT_VENTE") REFERENCES "ALILO"."UNITE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."PRODUIT" ADD CONSTRAINT "PROD_EMB_FK" FOREIGN KEY ("ID_UNIT_SEUIL") REFERENCES "ALILO"."EMBALLAGE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."EMBALLAGE" ADD CONSTRAINT "EMB_UNITE_FK" FOREIGN KEY ("ID_UNITE") REFERENCES "ALILO"."UNITE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."LIGNE_ACHAT" ADD CONSTRAINT "L_ACH_ACH_FK" FOREIGN KEY ("ID_ACHAT") REFERENCES "ALILO"."ACHAT" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."LIGNE_ACHAT" ADD CONSTRAINT "L_ACH_PROD_FK" FOREIGN KEY ("ID_PROD") REFERENCES "ALILO"."PRODUIT" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."LIGNE_ACHAT" ADD CONSTRAINT "L_ACH_EMB_FK" FOREIGN KEY ("UNITE_ACHAT") REFERENCES "ALILO"."EMBALLAGE" ("ID") ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."ARTICLE" ADD CONSTRAINT "ART_L_ACHAT_FK" FOREIGN KEY ("ID_L_ACHAT") REFERENCES "ALILO"."LIGNE_ACHAT" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "ALILO"."REGLEMENT_CL" ADD CONSTRAINT "VRS_CL_VNT_FK" FOREIGN KEY ("ID_VNT_CL") REFERENCES "ALILO"."VENTE_CL" ("ID") ON DELETE CASCADE ON UPDATE RESTRICT;

-- ----------------------------------------------
-- DDL Statements for checks
-- ----------------------------------------------

ALTER TABLE "ALILO"."ARTICLE" ADD CONSTRAINT "CHECK_QTE_STK" CHECK (QTE_STK_REEL >= 0);

-- ----------------------------------------------
-- DDL Statements for views
-- ----------------------------------------------

SET SCHEMA "ALILO";
CREATE VIEW V_FOURNISSEUR AS SELECT FOUR.ID, "NAME" AS "Fournisseur", ADR AS "Adresse", TEL AS "N° Tel", FOUR.CREDIT AS "Dettes(DA)"   FROM FOURNISSEUR FOUR;

SET SCHEMA "ALILO";
CREATE VIEW V_FAMILLE (ID, "Famille", "TVA %") AS SELECT * FROM FAMILLE;

SET SCHEMA "ALILO";
CREATE VIEW V_CATEGORIE (ID, ID_FAM, "Catégorie") AS SELECT ID, ID_FAM, DES FROM CATEGORIE;

SET SCHEMA "ALILO";
CREATE VIEW V_ROLE_UTILIS AS SELECT ID, DES AS "Rôle.Utilisateur" FROM ROLE_UTILIS;

SET SCHEMA "ALILO";
CREATE VIEW V_UNITE (ID, "Unité De Mésure") AS  SELECT ID, DES FROM UNITE;

SET SCHEMA "ALILO";
CREATE VIEW V_EMBALLAGE AS SELECT EMB.ID, ID_UNITE, EMB.DES AS "Emballage", U.DES AS "Unité", QTE_LOT AS "Unité (X)", QTE_LOT_DECIMAL AS "Unité (/)"  FROM EMBALLAGE EMB INNER JOIN UNITE U ON EMB.ID_UNITE = U.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_STOCK (ID, "Adresse") AS SELECT ID, ADR FROM STOCK;

SET SCHEMA "ALILO";
CREATE VIEW V_STOCKER AS SELECT S.ID, S.ID_PROD, S.ID_STOCK, P.DES AS "Produit", STK.ADR AS "Stock"  FROM (STOCKER S INNER JOIN PRODUIT P ON P.ID = S.ID_PROD) INNER JOIN STOCK STK ON STK.ID = S.ID_STOCK;

SET SCHEMA "ALILO";
CREATE VIEW V_PRODUIT AS SELECT PROD.ID, PROD.ID_CATEG, CAT.ID_FAM, PROD.REFER AS "Réf", PROD.DES AS "Produit", PROD.S_STK AS "Seuil.Stk", PROD.MARGE_GR AS "Marge.Gr", PROD.MARGE_DT AS "Marge.Dt"  FROM PRODUIT PROD INNER JOIN CATEGORIE CAT ON PROD.ID_CATEG = CAT.ID GROUP BY  PROD.ID, PROD.ID_CATEG, CAT.ID_FAM, PROD.REFER, PROD.DES, PROD.S_STK, PROD.MARGE_GR, PROD.MARGE_DT;

SET SCHEMA "ALILO";
CREATE VIEW V_QUANTIFIER AS SELECT Q.ID, Q.ID_PROD, Q.ID_EMB, P.DES AS "Produit", E.DES AS "Emballage", E.QTE_LOT AS "Qte.Lot", E.QTE_LOT_DECIMAL AS "Qte.Lot.Decimal"  FROM (QUANTIFIER Q INNER JOIN PRODUIT P ON P.ID = Q.ID_PROD) INNER JOIN EMBALLAGE E ON E.ID = Q.ID_EMB;

SET SCHEMA "ALILO";
CREATE VIEW V_ACHAT_ALL AS SELECT ACH.ID, ACH.NUM AS "N°", ACH."DATE" AS "Date.Achat", FOUR."NAME" AS "Fournisseur",      ACH.TOTAL AS "Total.(DA)", ACH_FR.TOTAL_VERSS AS "Montant.Versé(DA)",      ACH.VALIDE = 'Y' AS "Validé?", ((ACH.TOTAL <= ACH_FR.TOTAL_VERSS) OR (ACH.VALIDE = 'Y' AND FOUR."NAME" IS NULL)) AS "Réglé?" FROM ACHAT ACH LEFT JOIN (ACHAT_FOUR ACH_FR INNER JOIN FOURNISSEUR FOUR                                                ON ACH_FR.ID_FOUR = FOUR.ID)                 ON ACH.ID = ACH_FR.ID_ACHAT ORDER BY ACH."DATE" DESC;

SET SCHEMA "ALILO";
CREATE VIEW V_ACHAT_FOUR_ONLY AS SELECT ACH_FR.ID, ACH_FR.ID_ACHAT, ACH.NUM AS "N°", ACH."DATE" AS "Date.Achat", FOUR."NAME" AS "Fournisseur",      ACH.TOTAL AS "Total.(DA)", ACH_FR.TOTAL_VERSS AS "Montant.Versé(DA)",      ACH.VALIDE = 'Y' AS "Validé?", ((ACH.TOTAL <= ACH_FR.TOTAL_VERSS) OR (ACH.VALIDE = 'Y' AND FOUR."NAME" IS NULL)) AS "Réglé?" FROM ACHAT ACH INNER JOIN (ACHAT_FOUR ACH_FR INNER JOIN FOURNISSEUR FOUR                                                ON ACH_FR.ID_FOUR = FOUR.ID)                 ON ACH.ID = ACH_FR.ID_ACHAT ORDER BY ACH."DATE" DESC;

SET SCHEMA "ALILO";
CREATE VIEW V_LIGNE_ACHAT AS SELECT LACH.ID, LACH.ID_ACHAT, LACH.ID_PROD, PROD.REFER AS "Réf", PROD.DES AS "Produit", LACH.PU_ACHAT AS "PU.Achat", LACH.QTE_ACHETE AS "Qte.Achetée", EMB.DES AS "Unité",          LACH.TOTAL_LACH AS "Total(DA)" FROM (LIGNE_ACHAT LACH INNER JOIN EMBALLAGE EMB                          ON LACH.UNITE_ACHAT = EMB.ID) INNER JOIN PRODUIT PROD                                                          ON LACH.ID_PROD = PROD.ID ORDER BY LACH.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_VENTE_CL AS SELECT VNT.ID, VNT_CL.ID AS "ID_VNT_CL" , VNT.NUM AS "N°", VNT."DATE" AS "Date.Vente", VNT.HEURE AS "Heure", CL."NAME" AS "Client", VNT.TYPE_VNT AS "Mode",          VNT.TOTAL AS "Total(DA)", VNT_CL.TOTAL_VERSS AS "Montant.Versé(DA)",         VNT.VALIDE = 'Y' AS "Validé?", (VNT.TOTAL <= VNT_CL.TOTAL_VERSS) AS "Réglé?" FROM  (VENTE VNT INNER JOIN (VENTE_CL VNT_CL INNER JOIN CLIENT CL                                               ON VNT_CL.ID_CL = CL.ID )                 ON VNT.ID = VNT_CL.ID_VNT) ORDER BY VNT."DATE" DESC;

SET SCHEMA "ALILO";
CREATE VIEW V_VENTE_ALL AS SELECT VNT.ID, VNT.NUM AS "N°", VNT."DATE" AS "Date.Vente", VNT.HEURE AS "Heure", CL."NAME" AS "Client", VNT.TYPE_VNT AS "Mode",      VNT.TOTAL AS "Total(DA)", VNT_CL.TOTAL_VERSS AS "Montant.Versé(DA)",      VNT.VALIDE = 'Y' AS "Validé?", ((VNT.TOTAL <= VNT_CL.TOTAL_VERSS) OR (VNT.VALIDE = 'Y' AND CL."NAME" IS NULL)) AS "Réglé?"  FROM  (VENTE VNT LEFT JOIN (VENTE_CL VNT_CL INNER JOIN CLIENT CL                                              ON VNT_CL.ID_CL = CL.ID)                  ON VNT.ID = VNT_CL.ID_VNT) ORDER BY VNT."DATE" DESC;

SET SCHEMA "ALILO";
CREATE VIEW V_REGLEMENT_FOUR AS SELECT REG.ID, ACH_F.ID_FOUR, REG.ID_ACH_FR, FOUR."NAME" AS "Fournisseur", REG.MONTANT AS "Montant Versé", REG.DATE_VERS AS "Date.Versement", REG.TYPE_PAY AS "Mode.Payement"   FROM (REGLEMENT_FOUR REG INNER JOIN ACHAT_FOUR ACH_F                           ON REG.ID_ACH_FR = ACH_F.ID) INNER JOIN FOURNISSEUR FOUR ON ACH_F.ID_FOUR = FOUR.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_ARTICLE_TOUS AS SELECT ART.ID, ART.ID_L_ACHAT, LACH.ID_PROD, PROD.ID_CATEG, CAT.ID_FAM, PROD.REFER AS "Réf", PROD.DES AS "Produit",  LACH.PU_ACHAT AS "PU.Achat", PU_VENTE_GR AS "PU.Vente.Gr", PU_VENTE_DT AS "PU.Vente.Dt",  QTE_STK_REEL AS "Qte.Stk", QTE_EN_VRAC AS "Qte.En.Vrac", ACTIVE  FROM ((ARTICLE ART INNER JOIN LIGNE_ACHAT LACH                    ON ART.ID_L_ACHAT = LACH.ID) INNER JOIN (PRODUIT PROD INNER JOIN CATEGORIE CAT                                                                          ON PROD.ID_CATEG = CAT.ID)                                                 ON LACH.ID_PROD = PROD.ID) GROUP BY ART.ID, ART.ID_L_ACHAT, LACH.ID_PROD, PROD.ID_CATEG, CAT.ID_FAM, PROD.REFER, PROD.DES, LACH.PU_ACHAT, PU_VENTE_GR, PU_VENTE_DT, QTE_STK_REEL, QTE_EN_VRAC, ACTIVE ORDER BY ART.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_ARTICLE_ACTIVE AS SELECT * FROM V_ARTICLE_TOUS WHERE ACTIVE = 'Y';

SET SCHEMA "ALILO";
CREATE VIEW V_ARTICLE_A_VENDRE AS  SELECT * FROM V_ARTICLE_ACTIVE WHERE ("Qte.Stk" != 0 OR "Qte.En.Vrac" != 0);

SET SCHEMA "ALILO";
CREATE VIEW V_BENIFICE_ART AS SELECT ART.ID, ART.ID_L_ACHAT, LACH.ID_PROD, PROD.ID_CATEG, CAT.ID_FAM, PROD.REFER AS "Réf", PROD.DES AS "Produit",      QTE_STK_REEL AS "Qte.Stk", QTE_EN_VRAC AS "Qte.En.Vrac", LACH.QTE_ACHETE AS "Qte.Achté", EMB.DES AS "Unité.Achat", LACH.PU_ACHAT AS "PU.Achat",     SUM(LVNT.QTE_VEND_COLIS) AS "Qte.Vend.Coli", SUM(LVNT.QTE_VEND_VRAC) AS "Qte.Vend.Vrac" , CAST (LACH.TOTAL_LACH / SUM(LVNT.QTE_VEND_COLIS)AS DECIMAL (10,2)) AS "PU.Ach.Estimé" FROM ((ARTICLE ART INNER JOIN (LIGNE_ACHAT LACH INNER JOIN EMBALLAGE EMB                                                 ON LACH.UNITE_ACHAT = EMB.ID)                    ON ART.ID_L_ACHAT = LACH.ID) INNER JOIN (PRODUIT PROD INNER JOIN CATEGORIE CAT                                                                          ON PROD.ID_CATEG = CAT.ID)                                                 ON LACH.ID_PROD = PROD.ID) INNER JOIN LIGNE_VNT LVNT                                                                             ON LVNT.VALIDEE = 'Y'                                                                             AND LVNT.QTE_VEND_COLIS != 0                                                                             AND LVNT.ID_ART = ART.ID GROUP BY ART.ID, ART.ID_L_ACHAT, LACH.ID_PROD, PROD.ID_CATEG, CAT.ID_FAM, PROD.REFER, PROD.DES, LACH.PU_ACHAT, PU_VENTE_GR, PU_VENTE_DT, QTE_STK_REEL, QTE_EN_VRAC, QTE_ACHETE, EMB.DES, TOTAL_LACH ORDER BY ART.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_LIGNE_VENTE AS SELECT LVNT.ID, LVNT.ID_VNT, LVNT.ID_ART, PROD.REFER AS "Réf", PROD.DES AS "Produit", LVNT.PU_VNT AS "PU.Vente",          LVNT.QTE_VENDU AS "Qte.Vendue", EMB.DES AS "Unité.Vente", LVNT.TOTAL_LVNT AS "Total(DA)" FROM (LIGNE_VNT LVNT INNER JOIN EMBALLAGE EMB                          ON LVNT.UNITE_VNT = EMB.ID) INNER JOIN (ARTICLE ART INNER JOIN (LIGNE_ACHAT LACH INNER JOIN PRODUIT PROD                                                                                                            ON LACH.ID_PROD = PROD.ID)                                                                                ON ART.ID_L_ACHAT = LACH.ID)                                                       ON LVNT.ID_ART = ART.ID ORDER BY LVNT.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_UTILISATEUR AS SELECT U.ID, LOGIN AS "Nom.Utilisateur", R.DES AS "Rôle" FROM UTILISATEUR U INNER JOIN ROLE_UTILIS R ON U.ID_ROLE = R.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_REGLEMENT_CL AS SELECT REG.ID, VNT_CL.ID_CL, REG.ID_VNT_CL, CL."NAME" AS "Client", REG.MONTANT AS "Montant Versé", REG.DATE_VERS AS "Date.Versement", REG.TYPE_PAY AS "Mode.Paiement"   FROM (REGLEMENT_CL REG INNER JOIN VENTE_CL VNT_CL                           ON REG.ID_VNT_CL = VNT_CL.ID) INNER JOIN CLIENT CL                                                          ON VNT_CL.ID_CL = CL.ID;

SET SCHEMA "ALILO";
CREATE VIEW V_CLIENT AS SELECT CL.ID, "NAME" AS "Client", ADR AS "Adresse", TEL AS "N° Tel", APP_TVA AS "App.TVA", CREDIT + CREDIT_INITIAL AS "Dettes(DA)"        FROM CLIENT CL;

-- Reverting back to default schema 'APP'
SET SCHEMA "APP";

-- ----------------------------------------------
-- DDL Statements for triggers
-- ----------------------------------------------

CREATE TRIGGER "ALILO"."T_AFT_UPD_VALID_ACH_UPD_FOUR" AFTER UPDATE OF "VALIDE" ON "ALILO"."ACHAT" REFERENCING NEW AS NEW_ACH FOR EACH ROW UPDATE FOURNISSEUR SET          CREDIT          = CASE WHEN NEW_ACH.VALIDE = 'Y' THEN                             CREDIT            + NEW_ACH.TOTAL                           ELSE                             CREDIT            - NEW_ACH.TOTAL END     WHERE ID = (SELECT ID_FOUR FROM ACHAT_FOUR WHERE ID_ACHAT = NEW_ACH.ID);

CREATE TRIGGER "ALILO"."T_AFT_UPD_EMB_UPD_UNIT" AFTER UPDATE OF "DES" ON "ALILO"."EMBALLAGE" REFERENCING NEW AS NEW_EMB FOR EACH ROW UPDATE UNITE SET              DES = NEW_EMB.DES      WHERE   NEW_EMB.QTE_LOT = 1     AND     NEW_EMB.QTE_LOT_DECIMAL = 1     AND ID = NEW_EMB.ID_UNITE;

CREATE TRIGGER "ALILO"."T_AFT_DEL_ART_DEL_LACH" AFTER DELETE ON "ALILO"."ARTICLE" REFERENCING OLD AS DELETED_ROW FOR EACH ROW DELETE FROM LIGNE_ACHAT     WHERE ID = DELETED_ROW.ID_L_ACHAT;

CREATE TRIGGER "ALILO"."T_AFT_INS_LACH_UPD_ACH" AFTER INSERT ON "ALILO"."LIGNE_ACHAT" REFERENCING NEW AS NEW_LACH FOR EACH ROW UPDATE ACHAT SET          TOTAL = TOTAL + NEW_LACH.TOTAL_LACH     WHERE ID = NEW_LACH.ID_ACHAT;

CREATE TRIGGER "ALILO"."T_AFT_UPD_LACH_UPD_ACH" AFTER UPDATE ON "ALILO"."LIGNE_ACHAT" REFERENCING OLD AS OLD_LACH NEW AS NEW_LACH FOR EACH ROW UPDATE ACHAT SET          TOTAL = TOTAL - OLD_LACH.TOTAL_LACH + NEW_LACH.TOTAL_LACH     WHERE ID = NEW_LACH.ID_ACHAT;

CREATE TRIGGER "ALILO"."T_AFT_DEL_LACH_UPD_ACH" AFTER DELETE ON "ALILO"."LIGNE_ACHAT" REFERENCING OLD AS DEL_LACH FOR EACH ROW UPDATE ACHAT SET          TOTAL = TOTAL - DEL_LACH.TOTAL_LACH     WHERE ID = DEL_LACH.ID_ACHAT;

CREATE TRIGGER "ALILO"."T_AFT_VALID_LVNT_UPD_ART" AFTER UPDATE OF "VALIDEE" ON "ALILO"."LIGNE_VNT" REFERENCING NEW AS LVNT FOR EACH ROW UPDATE ARTICLE ART SET          QTE_STK_REEL =  CASE WHEN LVNT.VALIDEE = 'Y' THEN                              (CASE WHEN LVNT.QTE_VEND_VRAC <= ART.QTE_EN_VRAC THEN                                  QTE_STK_REEL - LVNT.QTE_VEND_COLIS                             ELSE                                  QTE_STK_REEL - LVNT.QTE_VEND_COLIS - 1                             END)                         ELSE                              (QTE_STK_REEL + LVNT.QTE_VEND_COLIS +                                CAST(FLOOR((LVNT.QTE_VEND_VRAC + ART.QTE_EN_VRAC)/                                             (SELECT QTE_LOT_DECIMAL FROM EMBALLAGE WHERE ID = LVNT.UNITE_VNT))                                  AS INT))                         END,          QTE_EN_VRAC =  CASE WHEN LVNT.VALIDEE = 'Y' THEN                              CASE WHEN LVNT.QTE_VEND_VRAC <= ART.QTE_EN_VRAC THEN                                  QTE_EN_VRAC - LVNT.QTE_VEND_VRAC                             ELSE                                  (SELECT QTE_LOT_DECIMAL FROM EMBALLAGE WHERE ID = LVNT.UNITE_VNT)                                     - (LVNT.QTE_VEND_VRAC - QTE_EN_VRAC)                             END                         ELSE                              MOD((QTE_EN_VRAC + LVNT.QTE_VEND_VRAC),                                             (SELECT QTE_LOT_DECIMAL FROM EMBALLAGE WHERE ID = LVNT.UNITE_VNT))                          END     WHERE ART.ID = LVNT.ID_ART;

CREATE TRIGGER "ALILO"."T_AFT_INS_LVNT_UPD_VNT" AFTER INSERT ON "ALILO"."LIGNE_VNT" REFERENCING NEW AS NEW_LVNT FOR EACH ROW UPDATE VENTE SET          TOTAL = TOTAL + NEW_LVNT.TOTAL_LVNT       WHERE ID = NEW_LVNT.ID_VNT;

CREATE TRIGGER "ALILO"."T_AFT_UPD_LVNT_UPD_VNT" AFTER UPDATE ON "ALILO"."LIGNE_VNT" REFERENCING OLD AS OLD_LVNT NEW AS NEW_LVNT FOR EACH ROW UPDATE VENTE SET          TOTAL           = TOTAL - OLD_LVNT.TOTAL_LVNT + NEW_LVNT.TOTAL_LVNT     WHERE ID = NEW_LVNT.ID_VNT;

CREATE TRIGGER "ALILO"."T_AFT_DEL_LVNT_UPD_VNT" AFTER DELETE ON "ALILO"."LIGNE_VNT" REFERENCING OLD AS DEL_LVNT FOR EACH ROW UPDATE VENTE SET          TOTAL = TOTAL - DEL_LVNT.TOTAL_LVNT     WHERE ID = DEL_LVNT.ID_VNT;

CREATE TRIGGER "ALILO"."T_AFT_UPD_PROD_UPD_QUANTIF" AFTER UPDATE OF "ID_UNIT_VENTE" ON "ALILO"."PRODUIT" REFERENCING NEW AS NEW_PROD FOR EACH ROW DELETE FROM QUANTIFIER     WHERE QUANTIFIER.ID_PROD = NEW_PROD.ID;

CREATE TRIGGER "ALILO"."T_AFT_UPD_VALID_ACH_UPD_ACTIVE_ART" AFTER UPDATE OF "VALIDE" ON "ALILO"."ACHAT" REFERENCING NEW AS NEW_ACH FOR EACH ROW UPDATE ARTICLE SET ACTIVE = NEW_ACH.VALIDE     WHERE ID_L_ACHAT IN (SELECT ID FROM LIGNE_ACHAT WHERE ID_ACHAT = NEW_ACH.ID);

CREATE TRIGGER "ALILO"."T_AFT_INS_REGCL_UPD_VNTCL" AFTER INSERT ON "ALILO"."REGLEMENT_CL" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE VENTE_CL VCL SET         VCL.TOTAL_VERSS = VCL.TOTAL_VERSS + NEW_REG.MONTANT     WHERE VCL.ID = NEW_REG.ID_VNT_CL;

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGCL_UPD_OLD_VNTCL" AFTER UPDATE ON "ALILO"."REGLEMENT_CL" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE VENTE_CL VCL SET         VCL.TOTAL_VERSS = VCL.TOTAL_VERSS - OLD_REG.MONTANT     WHERE VCL.ID = OLD_REG.ID_VNT_CL;

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGCL_UPD_NEW_VNTCL" AFTER UPDATE ON "ALILO"."REGLEMENT_CL" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE VENTE_CL VCL SET         VCL.TOTAL_VERSS = VCL.TOTAL_VERSS + NEW_REG.MONTANT     WHERE VCL.ID = NEW_REG.ID_VNT_CL;

CREATE TRIGGER "ALILO"."T_AFT_DEL_REGCL_UPD_VNTCL" AFTER DELETE ON "ALILO"."REGLEMENT_CL" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE VENTE_CL VCL SET         VCL.TOTAL_VERSS = VCL.TOTAL_VERSS - OLD_REG.MONTANT     WHERE VCL.ID = OLD_REG.ID_VNT_CL;

CREATE TRIGGER "ALILO"."T_AFT_INS_REGCL_UPD_CL" AFTER INSERT ON "ALILO"."REGLEMENT_CL" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE CLIENT CL SET         CL.CREDIT = CL.CREDIT - NEW_REG.MONTANT     WHERE CL.ID = (SELECT ID_CL FROM VENTE_CL WHERE ID = NEW_REG.ID_VNT_CL);

CREATE TRIGGER "ALILO"."T_AFT_DEL_REGCL_UPD_CL" AFTER DELETE ON "ALILO"."REGLEMENT_CL" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE CLIENT CL SET         CL.CREDIT = CL.CREDIT + OLD_REG.MONTANT     WHERE CL.ID = (SELECT ID_CL FROM VENTE_CL WHERE ID = OLD_REG.ID_VNT_CL);

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGCL_UPD_OLD_CL" AFTER UPDATE ON "ALILO"."REGLEMENT_CL" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE CLIENT CL SET         CL.CREDIT           = CL.CREDIT + OLD_REG.MONTANT     WHERE CL.ID = (SELECT ID_CL FROM VENTE_CL WHERE ID = OLD_REG.ID_VNT_CL);

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGCL_UPD_NEW_CL" AFTER UPDATE ON "ALILO"."REGLEMENT_CL" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE CLIENT CL SET         CL.CREDIT           = CL.CREDIT - NEW_REG.MONTANT     WHERE CL.ID = (SELECT ID_CL FROM VENTE_CL WHERE ID = NEW_REG.ID_VNT_CL);

CREATE TRIGGER "ALILO"."T_AFT_INS_REGFOUR_UPD_ACHFOUR" AFTER INSERT ON "ALILO"."REGLEMENT_FOUR" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE ACHAT_FOUR SET         TOTAL_VERSS = TOTAL_VERSS + NEW_REG.MONTANT     WHERE ACHAT_FOUR.ID = NEW_REG.ID_ACH_FR;

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGFOUR_UPD_OLD_ACHFOUR" AFTER UPDATE ON "ALILO"."REGLEMENT_FOUR" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE ACHAT_FOUR SET         TOTAL_VERSS = TOTAL_VERSS - OLD_REG.MONTANT     WHERE ACHAT_FOUR.ID = OLD_REG.ID_ACH_FR;

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGFOUR_UPD_NEW_ACHFOUR" AFTER UPDATE ON "ALILO"."REGLEMENT_FOUR" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE ACHAT_FOUR SET         TOTAL_VERSS = TOTAL_VERSS + NEW_REG.MONTANT     WHERE ACHAT_FOUR.ID = NEW_REG.ID_ACH_FR;

CREATE TRIGGER "ALILO"."T_AFT_DEL_REGFOUR_UPD_ACHFOUR" AFTER DELETE ON "ALILO"."REGLEMENT_FOUR" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE ACHAT_FOUR SET         TOTAL_VERSS = TOTAL_VERSS - OLD_REG.MONTANT     WHERE ACHAT_FOUR.ID = OLD_REG.ID_ACH_FR;

CREATE TRIGGER "ALILO"."T_AFT_INS_REGFOUR_UPD_FOUR" AFTER INSERT ON "ALILO"."REGLEMENT_FOUR" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE FOURNISSEUR FOUR  SET         FOUR.CREDIT = FOUR.CREDIT - NEW_REG.MONTANT     WHERE FOUR.ID = (SELECT ID_FOUR FROM ACHAT_FOUR WHERE ID = NEW_REG.ID_ACH_FR);

CREATE TRIGGER "ALILO"."T_AFT_DEL_REGFOUR_UPD_FOUR" AFTER DELETE ON "ALILO"."REGLEMENT_FOUR" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE FOURNISSEUR FOUR SET         FOUR.CREDIT = FOUR.CREDIT + OLD_REG.MONTANT     WHERE FOUR.ID = (SELECT ID_FOUR FROM ACHAT_FOUR WHERE ID = OLD_REG.ID_ACH_FR);

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGFOUR_UPD_OLD_FOUR" AFTER UPDATE ON "ALILO"."REGLEMENT_FOUR" REFERENCING OLD AS OLD_REG FOR EACH ROW UPDATE FOURNISSEUR FOUR SET         FOUR.CREDIT = FOUR.CREDIT + OLD_REG.MONTANT     WHERE FOUR.ID = (SELECT ID_FOUR FROM ACHAT_FOUR WHERE ID = OLD_REG.ID_ACH_FR);

CREATE TRIGGER "ALILO"."T_AFT_UPD_REGFOUR_UPD_NEW_FOUR" AFTER UPDATE ON "ALILO"."REGLEMENT_FOUR" REFERENCING NEW AS NEW_REG FOR EACH ROW UPDATE FOURNISSEUR FOUR SET         FOUR.CREDIT           = FOUR.CREDIT - NEW_REG.MONTANT     WHERE FOUR.ID = (SELECT ID_FOUR FROM ACHAT_FOUR WHERE ID = NEW_REG.ID_ACH_FR);

CREATE TRIGGER "ALILO"."T_AFT_UPD_UNIT_UPD_EMB" AFTER UPDATE ON "ALILO"."UNITE" REFERENCING NEW AS NEW_UNITE FOR EACH ROW UPDATE EMBALLAGE SET              DES = NEW_UNITE.DES      WHERE   DES != NEW_UNITE.DES     AND ID_UNITE = NEW_UNITE.ID     AND     QTE_LOT = 1     AND     QTE_LOT_DECIMAL = 1;

CREATE TRIGGER "ALILO"."T_AFT_UPD_VALID_VNT_UPD_VALID_LVNT" AFTER UPDATE OF "VALIDE" ON "ALILO"."VENTE" REFERENCING NEW AS VNT FOR EACH ROW UPDATE LIGNE_VNT LVNT      SET LVNT.VALIDEE = VNT.VALIDE     WHERE LVNT.ID_VNT = VNT.ID;

CREATE TRIGGER "ALILO"."T_AFT_UPD_VALID_VNT_DEL_REG_VNT" AFTER UPDATE OF "VALIDE" ON "ALILO"."VENTE" REFERENCING NEW AS NEW_VNT FOR EACH ROW DELETE FROM REGLEMENT_CL      WHERE NEW_VNT.VALIDE = 'N'     AND   ID_VNT_CL IN (SELECT  ID                           FROM    VENTE_CL                          WHERE   ID_VNT = NEW_VNT.ID);

CREATE TRIGGER "ALILO"."T_AFT_UPD_VALID_VNT_UPD_CL" AFTER UPDATE OF "VALIDE" ON "ALILO"."VENTE" REFERENCING NEW AS NEW_VNT FOR EACH ROW UPDATE CLIENT SET          CREDIT          = CASE WHEN NEW_VNT.VALIDE = 'Y' THEN                             CREDIT            + NEW_VNT.TOTAL                           ELSE                             CREDIT            - NEW_VNT.TOTAL END     WHERE ID = (SELECT ID_CL FROM VENTE_CL WHERE ID_VNT = NEW_VNT.ID);

CREATE TRIGGER "ALILO"."T_AFT_INS_UNIT_INS_EMB" AFTER INSERT ON "ALILO"."UNITE" REFERENCING NEW AS NEW_UNIT FOR EACH ROW INSERT INTO EMBALLAGE (DES, QTE_LOT, ID_UNITE, QTE_LOT_DECIMAL)      VALUES (NEW_UNIT.DES, 1, NEW_UNIT.ID, 1);

