/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.maj;

import entities.Categorie;
import entities.EntityClass;
import entities.Famille;
import java.awt.Component;
import javax.swing.JOptionPane;
import panels.crud.ListeFamillesPanel;
import dao.CategorieDAO;
import panels.CRUDPanel;

/**
 *
 * @author alilo
 */
public class MajCategoriePanel extends MajPanel<Categorie, CategorieDAO> {

    private final ListeFamillesPanel famillesPanel = new ListeFamillesPanel(this, false);
    private Famille famille;
    private String des;
    //private int idFam = 0;

    /**
     * Creates new form MajCategoriePanel
     *
     * @param listPanel
     */
    public MajCategoriePanel(CRUDPanel listPanel) {
        super(listPanel);
        initComponents();
        initMajPanel(fieldsPanel);
        selFamPanel.setSelListPanel(famillesPanel);
    }

    // Getters
    @Override
    public CategorieDAO getTableDAO() {
        return CategorieDAO.getInstance();
    }

    @Override
    public Component getDefaultFocusedComp() {
        return desField;
    }

    public void setFamille(Famille f) {
        sousFamChB.setSelected(f != null);
        famille = f;
        selFamPanel.setSelEntity(f);
    }

    @Override
    public void setChildEntity(EntityClass childEntity, boolean allowChng) {
        if (childEntity instanceof Famille) {
            //selFamPanel.setAllowSelChange(allowChng);
            setFamille((Famille) childEntity);
        }
    }

    @java.lang.Override
    public void initFields(Categorie oldEntity) {
        setFamille(oldEntity.getFamille());
        desField.setText(oldEntity.getDes());
    }

    @Override
    public boolean verifyFields() {
        String desTxt = desField.getText().trim();
        if (sousFamChB.isSelected()) {
            famille = selFamPanel.getSelEntity();
            if (famille == null) {
                JOptionPane.showMessageDialog(this, "Séléctionnez une famille SVP!!!", "Attention...", JOptionPane.WARNING_MESSAGE);
                selFamPanel.requestFocus();
                return false;
            }

        } else {
            famille = null;
        }

        if (desTxt.length() == 0) {
            JOptionPane.showMessageDialog(this, "Entrez la Désignation de cette catégorie SVP!!!", "Attention...", JOptionPane.WARNING_MESSAGE);
            desField.requestFocus();
            return false;
        }
        this.des = desTxt.toUpperCase();
        return true;
    }

    @Override
    public boolean save() {
        if (verifyFields()) {
            setEditedEntity(new Categorie(0, des, famille));
            return super.save();
        } else {
            setSaved(false);
            return false;
        }
    }

    @Override
    public void clearFields() {
        desField.setText("");
        desField.requestFocus();
        sousFamChB.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        sousFamChB = new javax.swing.JCheckBox();
        selFamPanel = new panels.SelectionPanel<Famille>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desField = new myComponents.MyJField();

        fieldsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        sousFamChB.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        sousFamChB.setText("C'est une Sous-Famille du:");
        sousFamChB.setBorder(null);
        sousFamChB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sousFamChBStateChanged(evt);
            }
        });
        jPanel1.add(sousFamChB);

        selFamPanel.setDescription("Séléctionner une famille!");
        selFamPanel.setEnabled(false);
        jPanel1.add(selFamPanel);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Désignation:");
        jPanel2.add(jLabel1);

        desField.setPrefsLangKey("MajCateg_Des_Lang");
        jPanel2.add(desField);

        javax.swing.GroupLayout fieldsPanelLayout = new javax.swing.GroupLayout(fieldsPanel);
        fieldsPanel.setLayout(fieldsPanelLayout);
        fieldsPanelLayout.setHorizontalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        fieldsPanelLayout.setVerticalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sousFamChBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sousFamChBStateChanged
        selFamPanel.setEnabled(sousFamChB.isSelected());
    }//GEN-LAST:event_sousFamChBStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private myComponents.MyJField desField;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private panels.SelectionPanel<Famille> selFamPanel;
    private javax.swing.JCheckBox sousFamChB;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MajCategoriePanel(null).showNewPanel(null);
            }
        });
    }
}
