/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myComponents;

import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.*;

/**
 *
 * @author alilo
 */
public class MyJTabbedPanTitle extends javax.swing.JPanel {

    private Container parent;
    private JTabbedPane tabbedPane;
    private Component titeledComponent;
    private JFrame f;
    private boolean maximized = false;

    /**
     * Creates new form MyJTabbedPanTitle
     */
    public MyJTabbedPanTitle() {
        initComponents();
    }

    public MyJTabbedPanTitle(String title, JTabbedPane parent, Component titledC) {
        initComponents();
        tabbedPane = parent;
        titeledComponent = titledC;
        titleLable.setText(title);
    }

    public MyJTabbedPanTitle(String title, Icon icon, JTabbedPane parent, Component titledC) {
        initComponents();
        tabbedPane = parent;
        titeledComponent = titledC;
        titleLable.setText(title);
        titleLable.setIcon(icon);
    }

    public void closeTab() {
        if (maximized) {
            main.MainApp.getInstance().getRootPanel().remove(this);
            main.MainApp.getInstance().getRootPanel().remove(titeledComponent);
            main.MainApp.getInstance().restorTopToolBar();
            main.MainApp.getInstance().restorCenterPanel();
        } else {
            tabbedPane.remove(titeledComponent);
        }
    }

    public void maximizeTab() {
        maximized = true;
        main.MainApp.getInstance().removeTopToolBar();
        main.MainApp.getInstance().removeCenterPanel();

        main.MainApp.getInstance().getRootPanel().add(this, BorderLayout.NORTH);
        main.MainApp.getInstance().getRootPanel().add(titeledComponent, BorderLayout.CENTER);
    }

    public void minimizeTab() {
        maximized = false;
        main.MainApp.getInstance().getRootPanel().remove(this);
        main.MainApp.getInstance().getRootPanel().remove(titeledComponent);
        
        tabbedPane.addTab(titleLable.getText(), titleLable.getIcon(), titeledComponent);
        tabbedPane.setSelectedComponent(titeledComponent);

        main.MainApp.getInstance().restorTopToolBar();
        main.MainApp.getInstance().restorCenterPanel();
    }
    Action closeTabAction = new AbstractAction() {

        {
            putValue(Action.SHORT_DESCRIPTION, "Fermer l'onglet");
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            closeTab();
        }
    };
    Action maxTabAction = new AbstractAction() {

        {
            putValue(Action.LARGE_ICON_KEY, new javax.swing.ImageIcon(getClass().getResource("/res/actions/fullScreen16.png")));
            putValue(Action.SHORT_DESCRIPTION, "Afficher en plain écran");
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            maximizeTab();
            maxButton.setAction(minTabAction);
        }
    };
    Action minTabAction = new AbstractAction() {

        {
            putValue(Action.LARGE_ICON_KEY, new javax.swing.ImageIcon(getClass().getResource("/res/actions/windowed16.png")));
            putValue(Action.SHORT_DESCRIPTION, "Sortir du plain ecran");
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            minimizeTab();
            maxButton.setAction(maxTabAction);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titleLable = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        maxButton = new com.l2fprod.common.swing.JLinkButton();
        closeButton = new com.l2fprod.common.swing.JLinkButton();

        setFocusable(false);
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        titleLable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLable.setText("Title");
        titleLable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        titleLable.setFocusable(false);
        titleLable.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(titleLable, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(filler2, gridBagConstraints);

        maxButton.setAction(maxTabAction);
        maxButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        maxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/fullScreen16.png"))); // NOI18N
        maxButton.setFocusable(false);
        maxButton.setRequestFocusEnabled(false);
        add(maxButton, new java.awt.GridBagConstraints());

        closeButton.setAction(closeTabAction);
        closeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/quit16.png"))); // NOI18N
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        add(closeButton, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.l2fprod.common.swing.JLinkButton closeButton;
    private javax.swing.Box.Filler filler2;
    private com.l2fprod.common.swing.JLinkButton maxButton;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables
}
