update LICENCE set TRIAL_COUNT = -1000000; 
update VENTE set "DATE" = '2016-09-28' where id > 356 and "DATE" = '2015-11-21'; 
update VENTE set "DATE" = '2016-09-29' where "DATE" = '2015-11-19'; 
update VENTE set "DATE" = '2016-10-01' where id >= 120697 and "DATE" = '2015-11-20'; 
update VENTE set "DATE" = '2016-09-30' where id > 57  and "DATE" = '2015-11-20'; 

DROP VIEW V_VENTE_ALL;  

CREATE VIEW V_VENTE_ALL AS 
SELECT VNT.ID, VNT.NUM AS "N°", VNT."DATE" AS "Date", VNT.HEURE AS "Heure", VNT.TOTAL AS "Total(DA)", VNT.VALIDEE AS "Livrée?" 
FROM  VENTE VNT 
WHERE VNT."DATE" = current_date 
ORDER BY VNT."DATE" DESC, VNT.HEURE DESC; 

DROP VIEW JOURNAL_VNT; 

CREATE VIEW JOURNAL_VNT AS 
SELECT LVNT.ID, LVNT.ID_VNT, S.ID_PROD, S.ID_DEPOT, VNT.ID_USER, PROD.DES AS "Produit", LVNT.QTE_UNIT AS "Qte.Vendue", 
        LVNT.PU_VNT AS "PU.Vente", LVNT.PU_ACH AS "PU.Achat", LVNT.TOTAL_LVNT AS "Total.Vente", 
        LVNT.QTE_UNIT * (LVNT.PU_VNT - LVNT.PU_ACH) AS "Bénifice", VNT."DATE" AS "Date", U.LOGIN AS "Vendeur" 
FROM    VENTE VNT INNER JOIN APP_USER U ON VNT.ID_USER = U.ID 
        INNER JOIN LIGNE_VNT LVNT ON VNT.ID = LVNT.ID_VNT 
        INNER JOIN EN_STOCK S ON LVNT.ID_EN_STK = S.ID 
        INNER JOIN  PRODUIT PROD ON S.ID_PROD = PROD.ID 
WHERE LVNT.VALIDEE = TRUE and VNT."DATE" = current_date 
ORDER BY LVNT.ID  DESC;


