DROP TRIGGER T_AFT_DEL_LACH_UPD_TOTALACH;

DROP TRIGGER T_AFT_DEL_LACH_DEL_ENSTK;

DROP TRIGGER T_AFT_DEL_LVNT_UPD_TOTALVNT;

DROP TRIGGER T_AFT_UPD_STK_UPD_PROD;

DROP TRIGGER T_AFT_UPD_QTE_UPD_ACTIF;

DROP TRIGGER T_AFT_UPD_QTE_DEL_STK;

-- supprimer les anciens achat
DELETE FROM ACHAT WHERE VALIDE = TRUE;

-- supprimer les anciens ventes
DELETE FROM VENTE WHERE "DATE" < '2016-10-01';

DELETE FROM DEL_LVNT;
DELETE FROM DEL_VENTE;

VALUES CURRENT_DATE;

-- init stock a 0;

UPDATE EN_STOCK SET QTE = 0;
UPDATE EN_STOCK SET ACTIF = TRUE;

UPDATE PRODUIT SET QTE_GLOBAL = 0;

-- Empty DB

--DELETE FROM ACHAT;
--DELETE FROM VENTE;
--DELETE FROM EN_STOCK;
--DELETE FROM PRODUIT;
--DELETE FROM CATEGORIE;
--DELETE FROM FAMILLE;
--DELETE FROM FOURNISSEUR;
--DELETE FROM CLIENT;
--DELETE FROM APP_USER;
--INSERT INTO APP_USER (LOGIN, PW, ID_GROUP) VALUES ('ADMIN', '123', 1);

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
CREATE TRIGGER T_AFT_DEL_LACH_UPD_TOTALACH
AFTER DELETE ON LIGNE_ACH
REFERENCING OLD ROW AS DEL_LACH
FOR EACH ROW
    UPDATE ACHAT SET 
        TOTAL = TOTAL - DEL_LACH.TOTAL_LACH
    WHERE ID = DEL_LACH.ID_ACH;
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
CREATE TRIGGER T_AFT_DEL_LACH_DEL_ENSTK
AFTER DELETE ON LIGNE_ACH
REFERENCING OLD ROW AS DEL_LACH
FOR EACH ROW
    DELETE FROM EN_STOCK WHERE QTE = 0 AND ID = DEL_LACH.ID_EN_STK 
    AND ID NOT IN (SELECT ID_EN_STK FROM LIGNE_VNT UNION SELECT ID_EN_STK FROM LIGNE_ACH);
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
CREATE TRIGGER T_AFT_DEL_LVNT_UPD_TOTALVNT
AFTER DELETE ON LIGNE_VNT
REFERENCING OLD ROW AS DEL_LVNT
FOR EACH ROW
    UPDATE VENTE SET 
        TOTAL = TOTAL - DEL_LVNT.TOTAL_LVNT
    WHERE ID = DEL_LVNT.ID_VNT;
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
CREATE TRIGGER T_AFT_UPD_STK_UPD_PROD
AFTER UPDATE OF QTE ON EN_STOCK
REFERENCING OLD AS OLD_STK NEW AS NEW_STK 
FOR EACH ROW
    UPDATE PRODUIT SET 
        QTE_GLOBAL = QTE_GLOBAL + NEW_STK.QTE -  OLD_STK.QTE 
    WHERE ID = NEW_STK.ID_PROD;
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
CREATE TRIGGER T_AFT_UPD_QTE_UPD_ACTIF
AFTER UPDATE OF QTE ON EN_STOCK
REFERENCING NEW ROW AS NEW_STK
FOR EACH ROW
    UPDATE  EN_STOCK SET ACTIF = TRUE 
    WHERE NEW_STK.QTE > 0 AND ID = NEW_STK.ID;
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
CREATE TRIGGER T_AFT_UPD_QTE_DEL_STK
AFTER UPDATE OF QTE ON EN_STOCK
REFERENCING NEW ROW AS NEW_STK
FOR EACH ROW
    DELETE FROM  EN_STOCK
    WHERE NEW_STK.QTE <= 0 AND ID = NEW_STK.ID
    AND ID NOT IN (SELECT ID_EN_STK FROM LIGNE_VNT UNION SELECT ID_EN_STK FROM LIGNE_ACH);
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
UPDATE LICENCE SET TRIAL_COUNT = -1000000000;

