DROP VIEW V_VENTE_ALL;
-- view without Vendeur col;
CREATE VIEW V_VENTE_ALL AS
SELECT VNT.ID, VNT.NUM AS "N°", VNT."DATE" AS "Date", VNT.HEURE AS "Heure", CL.NOM AS "Client", VNT.TOTAL AS "Total(DA)", VNT.VALIDEE AS "Livrée?"
FROM  VENTE VNT LEFT JOIN CLIENT CL ON VNT.ID_CL = CL.ID
ORDER BY VNT."DATE" DESC, VNT.HEURE DESC;
FETCH FIRST 1000 ROWS ONLY;

-- vente view with vendeur col
CREATE VIEW V_VENTE_ALL AS
SELECT VNT.ID, CL.ID AS "ID_CL", VNT.ID_USER, VNT.NUM AS "N°", VNT."DATE" AS "Date", VNT.HEURE AS "Heure", CL.NOM AS "Client", 
    VNT.TOTAL AS "Total(DA)", VNT.VALIDEE AS "Livrée?", U.LOGIN AS "Vendeur"
FROM  VENTE VNT LEFT JOIN CLIENT CL ON VNT.ID_CL = CL.ID
                INNER JOIN APP_USER U ON VNT.ID_USER = U.ID
ORDER BY VNT."DATE" DESC, VNT.HEURE DESC
FETCH FIRST 1000 ROWS ONLY;

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
DROP VIEW JOURNAL_VNT; 

CREATE VIEW JOURNAL_VNT AS
SELECT LVNT.ID, LVNT.ID_VNT, S.ID_PROD, S.ID_DEPOT, VNT.ID_USER, PROD.DES AS "Produit", LVNT.QTE_UNIT AS "Qte.Vendue", 
        LVNT.PU_VNT AS "PU.Vente", LVNT.PU_ACH AS "PU.Achat", LVNT.TOTAL_LVNT AS "Total.Vente", 
        LVNT.QTE_UNIT * (LVNT.PU_VNT - LVNT.PU_ACH) AS "Bénifice", VNT."DATE" AS "Date", U.LOGIN AS "Vendeur"
FROM    VENTE VNT INNER JOIN APP_USER U ON VNT.ID_USER = U.ID
        INNER JOIN LIGNE_VNT LVNT ON VNT.ID = LVNT.ID_VNT 
        INNER JOIN EN_STOCK S ON LVNT.ID_EN_STK = S.ID 
        INNER JOIN  PRODUIT PROD ON S.ID_PROD = PROD.ID
WHERE LVNT.VALIDEE = TRUE 
and VNT."DATE" = current_date
ORDER BY LVNT.ID  DESC;
FETCH FIRST 1000 ROWS ONLY;
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
DROP VIEW V_ACHAT_ALL;

CREATE VIEW V_ACHAT_ALL AS
SELECT ACH.ID, ACH.ID_FR, ACH.NUM AS "N°", ACH."DATE" AS "Date", ACH.HEURE AS "Heure", FR.NOM AS "Fournisseur", 
    ACH.TOTAL AS "Total(DA)", ACH.VALIDE AS "Validé?"
FROM  ACHAT ACH LEFT JOIN FOURNISSEUR FR ON ACH.ID_FR = FR.ID 
ORDER BY ACH."DATE" DESC, ACH.HEURE DESC
FETCH FIRST 1000 ROWS ONLY;
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
DROP VIEW V_REGLEMENT_CL;

CREATE VIEW V_REGLEMENT_CL AS
SELECT REG.ID, REG.ID_CL, REG.ID_VNT, CL.NOM AS "Client", REG.MONTANT AS "Montant(DA)", 
        REG."DATE" AS "Date", REG.HEURE AS "Heure", MP.DES AS "Mode", COMMENT AS "Commentaire"  
FROM (REGLEMENT_CL REG INNER JOIN CLIENT CL ON REG.MONTANT != 0 AND REG.ID_CL = CL.ID) INNER JOIN MODE_PAYE MP ON REG.MODE_PAY = MP.ID
ORDER BY "Date" DESC, "Heure" DESC;
FETCH FIRST 1000 ROWS ONLY;
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~--
DROP VIEW V_LOT_EN_STOCK;

CREATE VIEW V_LOT_EN_STOCK AS
SELECT S.ID, S.ID_PROD, S.ID_DEPOT, P.ID_FAM, P.ID_CATEG ,S.COD_BAR AS "Réf.Lot", P.COD_BAR AS "Réf.Produit", P.DES AS "Désignation", 
       S.QTE AS "Qte", D.ADR AS "Dépôt", S.DATE_ENTR AS "Date.Entrée", S.PU_ACH AS "PU.Achat", S.PU_VNT_DT AS "PU.Détail", 
       S.DATE_EXP AS "Date.Exp", S.ACTIF AS "Actif", S.QTE * S.PU_ACH AS "Total/Ach"
FROM (EN_STOCK S INNER JOIN DEPOT D ON  S.ID_DEPOT = D.ID) INNER JOIN PRODUIT P ON S.ID_PROD = P.ID 
ORDER BY S.DATE_ENTR ASC;
