/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CtegoriePanel.java
 *
 * Created on 17/10/2009, 11:25:33 ص
 */
package panels;

import java.awt.Frame;
import java.awt.Window;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import dao.TableDAO;

/**
 *
 * @author alilo
 */
public abstract class DefaultPanel extends JPanel {
    
    private Frame parentFrame = null;
    private Window parentWindow = null;
    
    public DefaultPanel() {
        super();
        initComponents();
    }
    
    // Setters
    public void setParentWindow(Window parentWindow) {
        this.parentWindow = parentWindow;
    }

    public void setParentFrame(Frame parentFrame) {
        this.parentFrame = parentFrame;
    }
    
    // Getters
    public Window getParentWindow() {
        return parentFrame;
    }

    public Frame getParentFrame() {
        return parentFrame;
    }
    
    public final JScrollPane getListScrollPan() {
        return listScrollPan;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolsPanel = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        findButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        insertButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        reloadButton = new javax.swing.JButton();
        filterField = new myComponents.MyJField();
        listScrollPan = new javax.swing.JScrollPane();
        summaryPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 450));
        setLayout(new java.awt.BorderLayout());

        toolsPanel.setLayout(new java.awt.BorderLayout());

        toolBar.setRollover(true);
        toolBar.setMinimumSize(new java.awt.Dimension(107, 29));
        toolBar.setPreferredSize(new java.awt.Dimension(30, 30));

        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/find.png"))); // NOI18N
        findButton.setFocusable(false);
        findButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        findButton.setPreferredSize(new java.awt.Dimension(27, 30));
        findButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        toolBar.add(findButton);
        toolBar.add(jSeparator7);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/new2..png"))); // NOI18N
        insertButton.setMnemonic(KeyEvent.VK_A);
        insertButton.setFocusable(false);
        insertButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        insertButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        toolBar.add(insertButton);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/edit16.2.png"))); // NOI18N
        editButton.setFocusable(false);
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        toolBar.add(editButton);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/delete2.png"))); // NOI18N
        deleteButton.setMnemonic(KeyEvent.VK_DELETE);
        deleteButton.setFocusable(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        toolBar.add(deleteButton);
        toolBar.add(jSeparator9);

        reloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/reload16.png"))); // NOI18N
        reloadButton.setFocusable(false);
        reloadButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reloadButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });
        toolBar.add(reloadButton);

        toolsPanel.add(toolBar, java.awt.BorderLayout.PAGE_START);

        filterField.setBackground(new java.awt.Color(255, 255, 204));
        filterField.setPreferredSize(new java.awt.Dimension(600, 23));
        filterField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filterFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterFieldKeyReleased(evt);
            }
        });
        toolsPanel.add(filterField, java.awt.BorderLayout.CENTER);

        add(toolsPanel, java.awt.BorderLayout.NORTH);

        listScrollPan.setFocusable(false);
        listScrollPan.setPreferredSize(new java.awt.Dimension(500, 300));
        add(listScrollPan, java.awt.BorderLayout.CENTER);

        summaryPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        summaryPanel.setLayout(new javax.swing.BoxLayout(summaryPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Sommaire:");
        jLabel6.setPreferredSize(new java.awt.Dimension(75, 15));
        summaryPanel.add(jLabel6);

        add(summaryPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        insert();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        edit();
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        delete();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
    }//GEN-LAST:event_findButtonActionPerformed

    private void filterFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterFieldKeyReleased
        filterList(filterField.getText().toUpperCase());
    }//GEN-LAST:event_filterFieldKeyReleased

    private void filterFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getListScrollPan().getComponent(0).requestFocus();
        }
    }//GEN-LAST:event_filterFieldKeyPressed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        reload();
        clearSelection();
    }//GEN-LAST:event_reloadButtonActionPerformed
    
    public abstract TableDAO getTableDAO();
    public abstract void insert();
    public abstract void edit();
    public abstract void delete();
    public abstract void reload();
    public abstract void clearSelection();
    /**
     * Filter the liste in the panel, based on input of filterFeild.
     * @param input 
     */
    public abstract void filterList(String input);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private myComponents.MyJField filterField;
    private javax.swing.JButton findButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JScrollPane listScrollPan;
    private javax.swing.JButton reloadButton;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JPanel toolsPanel;
    // End of variables declaration//GEN-END:variables
}
