/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import myComponents.MyJPanel;

/**
 *
 * @author alilo
 */
public abstract class SettingsPanel extends MyJPanel {

    /**
     * Creates new form SettingsPanel
     */

    /**
     * Creates new form SettingsPanel
     *
     * @param owner
     */
    public SettingsPanel(Container owner) {
        super(owner);
    }

    public void initSettingsPanel(Container settingsPanel) {
        initComponents();
        add(settingsPanel, BorderLayout.CENTER);
    }

    public void showSettings() {
        loadSettings();
        showPanel(true);
    }

    @Override
    public Component getDefaultFocusedComp() {
        return saveButton;
    }

    abstract public void loadSettings();

    abstract public boolean saveSettings();
    //
    private final Action saveAction = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            saveSettings();
        }
    };
    //
    private final Action okAction = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (saveSettings()) {
                dialog.closeDialog();
            }
        }
    };
    //
    private final Action cancelAction = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            dialog.closeDialog();
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currencyRadioGroup = new javax.swing.ButtonGroup();
        buttonsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        cancelButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        setLayout(new java.awt.BorderLayout());

        buttonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 0, 0));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.LINE_AXIS));

        okButton.setAction(okAction);
        okButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/ok16.png"))); // NOI18N
        okButton.setText("OK");
        buttonsPanel.add(okButton);

        saveButton.setAction(saveAction);
        saveButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/save16.png"))); // NOI18N
        saveButton.setText("Appliquer");
        buttonsPanel.add(saveButton);
        buttonsPanel.add(filler1);

        cancelButton.setAction(cancelAction);
        cancelButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/cancel16.png"))); // NOI18N
        cancelButton.setText("Annuler");
        buttonsPanel.add(cancelButton);

        add(buttonsPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.ButtonGroup currencyRadioGroup;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
