/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import com.l2fprod.common.swing.JFontChooser;
import dialogs.MyJDialog;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import myComponents.MyJTable;
import myModels.MyJTableCols2ListModel;
import tools.ExceptionReporting;

/**
 *
 * @author alilo
 */
public class TablePanelSettings extends SettingsPanel {

    private final RSTablePanel tablePanel;
    private MyJTableCols2ListModel filterColsListModel;
    private MyJTableCols2ListModel visibleColsListModel;
    private MyJTableCols2ListModel printColsListModel;

    private MyJDialog previewDialog;
    private JFontChooser fontChooser;
    private Font printFont;

    /**
     * Creates new form CRUDPanelSettings
     *
     * @param panel
     */
    public TablePanelSettings(RSTablePanel panel) {
        super(panel);
        initComponents();
        initSettingsPanel(settingsTabbedPane);

        tablePanel = panel;
    }

    @Override
    public void loadSettings() {
        switch (tablePanel.getFilterMode()) {
            case MyJTable.START_WITH_FILTER:
                startWithRadio.setSelected(true);
                break;
            case MyJTable.END_WITH_FILTER:
                endWithRadio.setSelected(true);
                break;
            case MyJTable.ANY_MATCH_FILTER:
                containsRadio.setSelected(true);
                break;
            case MyJTable.EXACT_MATCH_FILTER:
                exactRadio.setSelected(true);
                break;
        }

        visibleColsListModel = new MyJTableCols2ListModel(tablePanel.getTable(), MyJTableCols2ListModel.ALL_COLS);
        filterColsListModel = new MyJTableCols2ListModel(tablePanel.getTable(), MyJTableCols2ListModel.ONLY_VISIBLE_COLS);
        printColsListModel = new MyJTableCols2ListModel(tablePanel.getTable(), MyJTableCols2ListModel.ONLY_VISIBLE_COLS);

        visibleColsList.setModel(visibleColsListModel);
        filterColsList.setModel(filterColsListModel);
        printColsList.setModel(printColsListModel);

        filterColsListModel.setCheckedCols(tablePanel.getFilterColumns());
        visibleColsListModel.setCheckedCols(tablePanel.getVisibleCols());
    }

    @Override
    public boolean saveSettings() {
        if (startWithRadio.isSelected()) {
            tablePanel.setFilterMode(MyJTable.START_WITH_FILTER);
        }
        if (endWithRadio.isSelected()) {
            tablePanel.setFilterMode(MyJTable.END_WITH_FILTER);
        }
        if (containsRadio.isSelected()) {
            tablePanel.setFilterMode(MyJTable.ANY_MATCH_FILTER);
        }
        if (exactRadio.isSelected()) {
            tablePanel.setFilterMode(MyJTable.EXACT_MATCH_FILTER);
        }
        tablePanel.setFilterCols(filterColsListModel.getCheckedCols());
        tablePanel.setVisibleCols(visibleColsListModel.getCheckedCols());
        return true;
    }

    public void printTable() {
        MyJTable printTable = tablePanel.getTable().getPrintableTable();
        String[] printCols = printColsListModel.getCheckedCols();
        if(printCols.length == 0){
            JOptionPane.showMessageDialog(this, "Sélectionnez les collones a imprimer SVP!");
            return;
        }

        for (String col : printTable.getModel().getColNames()) {
            printTable.setColumnVisible(col, false);
        }
        for (String col : printCols) {
            printTable.setColumnVisible(col, true);

        }
        if (printFont != null) {
            printTable.setFont(printFont);
            printTable.setRowHeight(printFont.getSize() + 15);
        }

        if (previewDialog == null) {
            previewDialog = new MyJDialog(this, true, false);
            previewDialog.setPreferredSize(new Dimension(595, 842));
        }
        scrollPane.setViewportView(printTable);
        previewDialog.show(printTableP);

        try {
            MessageFormat title = new MessageFormat(printTitleField.getText());
            printTable.print(JTable.PrintMode.FIT_WIDTH, title, new MessageFormat("{0}"));
        } catch (PrinterException ex) {
            ExceptionReporting.showException(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filterModebuttonGroup = new javax.swing.ButtonGroup();
        settingsTabbedPane = new javax.swing.JTabbedPane();
        filterTab = new javax.swing.JPanel();
        startWithRadio = new javax.swing.JRadioButton();
        endWithRadio = new javax.swing.JRadioButton();
        containsRadio = new javax.swing.JRadioButton();
        exactRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        filterColsScrollPan = new javax.swing.JScrollPane();
        filterColsList = new myComponents.MyJListe();
        jLabel2 = new javax.swing.JLabel();
        viewTab = new javax.swing.JPanel();
        visibleColsScrollPane = new javax.swing.JScrollPane();
        visibleColsList = new myComponents.MyJListe();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        printTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        visibleColsScrollPane1 = new javax.swing.JScrollPane();
        printColsList = new myComponents.MyJListe();
        printTableBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        printTitleField = new javax.swing.JTextField();
        printTableP = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        printTableBtn1 = new javax.swing.JButton();

        filterTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 1, 0, 1, 0, 1, 0};
        jPanel1Layout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0};
        filterTab.setLayout(jPanel1Layout);

        filterModebuttonGroup.add(startWithRadio);
        startWithRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startWithRadio.setText("Commance Par");
        startWithRadio.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        filterTab.add(startWithRadio, gridBagConstraints);

        filterModebuttonGroup.add(endWithRadio);
        endWithRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endWithRadio.setText("Termine Par");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        filterTab.add(endWithRadio, gridBagConstraints);

        filterModebuttonGroup.add(containsRadio);
        containsRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        containsRadio.setText("Contient");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        filterTab.add(containsRadio, gridBagConstraints);

        filterModebuttonGroup.add(exactRadio);
        exactRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exactRadio.setText("Exact");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        filterTab.add(exactRadio, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Choisissez le mode de filtre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        filterTab.add(jLabel1, gridBagConstraints);

        filterColsList.setCheckable(true);
        filterColsScrollPan.setViewportView(filterColsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        filterTab.add(filterColsScrollPan, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Appliquer le filtre sur les colonnes sélectionnés:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        filterTab.add(jLabel2, gridBagConstraints);

        settingsTabbedPane.addTab("Filtrage", filterTab);

        viewTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        java.awt.GridBagLayout viewTabLayout = new java.awt.GridBagLayout();
        viewTabLayout.columnWidths = new int[] {0, 1, 0, 1, 0, 1, 0};
        viewTabLayout.rowHeights = new int[] {0, 3, 0, 3, 0};
        viewTab.setLayout(viewTabLayout);

        visibleColsList.setCheckable(true);
        visibleColsScrollPane.setViewportView(visibleColsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        viewTab.add(visibleColsScrollPane, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Choisissez les colonnes à afficher:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        viewTab.add(jLabel4, gridBagConstraints);

        jButton2.setText("Police ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        viewTab.add(jButton2, gridBagConstraints);

        settingsTabbedPane.addTab("Apparence", viewTab);

        printTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        printTab.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Choisissez les colonnes à imprimer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        printTab.add(jLabel5, gridBagConstraints);

        printColsList.setCheckable(true);
        visibleColsScrollPane1.setViewportView(printColsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        printTab.add(visibleColsScrollPane1, gridBagConstraints);

        printTableBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/print16.png"))); // NOI18N
        printTableBtn.setText("Imprimer la liste");
        printTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTableBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        printTab.add(printTableBtn, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Police d'impression");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        printTab.add(jButton1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Titre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printTab.add(jLabel3, gridBagConstraints);

        printTitleField.setForeground(new java.awt.Color(255, 0, 0));
        printTitleField.setText("Aucun Titre!");
        printTitleField.setMinimumSize(new java.awt.Dimension(4, 25));
        printTitleField.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        printTab.add(printTitleField, gridBagConstraints);

        settingsTabbedPane.addTab("Impression", printTab);

        printTableP.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        printTableP.add(scrollPane, gridBagConstraints);

        printTableBtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printTableBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/actions/print16.png"))); // NOI18N
        printTableBtn1.setText("Print");
        printTableBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTableBtn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        printTableP.add(printTableBtn1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void printTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTableBtnActionPerformed
        printTable();
    }//GEN-LAST:event_printTableBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (fontChooser == null) {
            fontChooser = new JFontChooser();
        }
        printFont = fontChooser.showFontDialog(this, "Choisir le police d'impression");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (fontChooser == null) {
            fontChooser = new JFontChooser();
        }
        Font font = fontChooser.showFontDialog(this, "Choisir le police");
        tablePanel.getTable().setFont(font);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void printTableBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTableBtn1ActionPerformed
        previewDialog.closeDialog();
    }//GEN-LAST:event_printTableBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton containsRadio;
    private javax.swing.JRadioButton endWithRadio;
    private javax.swing.JRadioButton exactRadio;
    private myComponents.MyJListe filterColsList;
    private javax.swing.JScrollPane filterColsScrollPan;
    private javax.swing.ButtonGroup filterModebuttonGroup;
    private javax.swing.JPanel filterTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private myComponents.MyJListe printColsList;
    private javax.swing.JPanel printTab;
    private javax.swing.JButton printTableBtn;
    private javax.swing.JButton printTableBtn1;
    private javax.swing.JPanel printTableP;
    private javax.swing.JTextField printTitleField;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTabbedPane settingsTabbedPane;
    private javax.swing.JRadioButton startWithRadio;
    private javax.swing.JPanel viewTab;
    private myComponents.MyJListe visibleColsList;
    private javax.swing.JScrollPane visibleColsScrollPane;
    private javax.swing.JScrollPane visibleColsScrollPane1;
    // End of variables declaration//GEN-END:variables
}
