/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.views;

import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import java.net.URL;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author alilo
 */
public class MontantPanel extends javax.swing.JPanel {

    private final DecimalFormat montantFormat = new DecimalFormat("###,##0.00");
    private String titleString;
    private String titleIcon;
    //private double totalDouble;
    private BigDecimal montant = new BigDecimal(0);
    private double montantDoubleValue;
    private Font titleFont;
    private Font montantFont;

    /**
     * Creates new form TotalPanel
     */
    public MontantPanel() {
        initComponents();
    }

    public void setTitleString(String titleString) {
        this.titleString = titleString;
        titelLabel.setText(titleString);
    }

    public String getTitleString() {
        return titleString;
    }

    public void setTitleIcon(String titleIcon) {
        this.titleIcon = titleIcon;
        URL iconURL = getClass().getResource(titleIcon);
        if (iconURL != null) {
            titelLabel.setIcon(new ImageIcon(iconURL));
        }else{
            titelLabel.setIcon(null);
        }
    }

    public String getTitleIcon() {
        return titleIcon;
    }

    public void setMontant(BigDecimal montant) {
        if (montant == null) {
            montant = new BigDecimal(0);
        }
        this.montant = montant;
        this.montantDoubleValue = montant.doubleValue();
        montantLabel.setText(montantFormat.format(montant));
        if (montantDoubleValue <= 0) {
            montantLabel.setForeground(Color.red);
        } else {
            montantLabel.setForeground(Color.GREEN);
        }
    }

    public BigDecimal getMontant() {
        return montant;
    }

    public void setMontantDoubleValue(double montantDoubleValue) {
        this.montantDoubleValue = montantDoubleValue;
        setMontant(new BigDecimal(montantDoubleValue));
    }

    public double getMontantDoubleValue() {
        return montantDoubleValue;
    }

    public void setTitleFont(Font titleFont) {
        this.titleFont = titleFont;
        titelLabel.setFont(titleFont);
    }

    public Font getTitleFont() {
        return titleFont;
    }

    public void setMontantFont(Font montantFont) {
        this.montantFont = montantFont;
        montantLabel.setFont(montantFont);
    }

    public Font getMontantFont() {
        return montantFont;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imagePanel1 = new myComponents.ImagePanel();
        titelLabel = new javax.swing.JLabel();
        montantLabel = new javax.swing.JLabel();
        blackBGLbl = new javax.swing.JLabel();

        imagePanel1.setImgLocationPath("/res/png/curvedPanel.png");
        imagePanel1.setMinimumSize(new java.awt.Dimension(50, 0));
        imagePanel1.setPreferredSize(new java.awt.Dimension(50, 4));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        titelLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        titelLabel.setForeground(new java.awt.Color(0, 255, 0));
        titelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/mony32.png"))); // NOI18N
        titelLabel.setText("Gt:");
        titelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        titelLabel.setFocusable(false);
        titelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(titelLabel, gridBagConstraints);

        montantLabel.setFont(new java.awt.Font("DS-Digital", 0, 56)); // NOI18N
        montantLabel.setForeground(new java.awt.Color(0, 255, 0));
        montantLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        montantLabel.setText("0.00");
        montantLabel.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(montantLabel, gridBagConstraints);

        blackBGLbl.setBackground(new java.awt.Color(0, 0, 0));
        blackBGLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(blackBGLbl, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blackBGLbl;
    private myComponents.ImagePanel imagePanel1;
    private javax.swing.JLabel montantLabel;
    private javax.swing.JLabel titelLabel;
    // End of variables declaration//GEN-END:variables
}
