/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.views;

import appLogic.Statistiques;
import entities.AppUser;
import entities.EntityClass;
import java.awt.BorderLayout;
import java.math.BigDecimal;
import java.util.Date;
import myComponents.MyJFrame;
import myComponents.MyJPanel;
import panels.crud.ListeVentesPanel;

/**
 *
 * @author alilo
 */
public class StatistiquesPanel extends MyJPanel {

    private AppUser user;
    private Date beginDate, endDate;
    private Statistiques stats;
    BigDecimal benifice = BigDecimal.ZERO;
    private final ListeVentesPanel ventesPanel = new ListeVentesPanel(this, false) {

        @Override
        public void setPeriod(Date beginDate, Date endDate) {
            super.setPeriod(beginDate, endDate);
            StatistiquesPanel.this.setPeriod(beginDate, endDate);
        }

        @Override
        public void setMasterEntity(EntityClass masterEntity) {
            super.setMasterEntity(masterEntity);
            if (masterEntity instanceof AppUser) {
                setUser((AppUser) masterEntity);
            }
        }
    };

    /**
     * Creates new form RecettePanel
     */
    public StatistiquesPanel() {
        initComponents();
        detailsTab.addTab("Journal des Ventes", ventesLB.getIcon(), ventesPanel);
        showTotals();
    }

    public void setPeriod(Date beginDate, Date endDate) {
        this.beginDate = beginDate;
        this.endDate = endDate;
        showTotals();
    }

    public void setUser(AppUser user) {
        this.user = user;
        showTotals();
    }

    public final void showTotals() {
        stats = Statistiques.getInstance(beginDate, endDate, user);
        recettePanel.setMontant(stats.getRecette());
        depensePanel.setMontant(stats.getTotalDepense());
        creditPanel.setMontant(stats.getTotalCred());
        caissePanel.setMontant(stats.getCaisse());
        benifice = stats.getBenifice();// the benifice will be shown on demande!!!!
        benificePanel.setMontant(BigDecimal.ZERO);
    }

    private void showBenif(boolean show) {
        if (show) {
            benificePanel.setMontant(benifice);
        } else {
            benificePanel.setMontant(BigDecimal.ZERO);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        benifMenu = new javax.swing.JPopupMenu();
        showBenif = new javax.swing.JMenuItem();
        hideBenif = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        totalsPanel = new javax.swing.JPanel();
        ventesLB = new com.l2fprod.common.swing.JLinkButton();
        recettePanel = new panels.views.MontantPanel();
        jLabel5 = new javax.swing.JLabel();
        creditPanel = new panels.views.MontantPanel();
        jLabel3 = new javax.swing.JLabel();
        depensePanel = new panels.views.MontantPanel();
        jLabel2 = new javax.swing.JLabel();
        caissePanel = new panels.views.MontantPanel();
        jLabel4 = new javax.swing.JLabel();
        benificePanel = new panels.views.MontantPanel();
        detailsTab = new javax.swing.JTabbedPane();

        showBenif.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        showBenif.setText("Afficher");
        showBenif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBenifActionPerformed(evt);
            }
        });
        benifMenu.add(showBenif);

        hideBenif.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        hideBenif.setText("Cacher");
        hideBenif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideBenifActionPerformed(evt);
            }
        });
        benifMenu.add(hideBenif);

        setFocusCycleRoot(true);
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(350);
        jSplitPane1.setDividerSize(15);
        jSplitPane1.setOneTouchExpandable(true);

        totalsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        totalsPanel.setOpaque(false);
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 0, 0};
        jPanel1Layout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        totalsPanel.setLayout(jPanel1Layout);

        ventesLB.setBackground(new java.awt.Color(0, 0, 0));
        ventesLB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 3));
        ventesLB.setForeground(new java.awt.Color(0, 255, 0));
        ventesLB.setText("Ventes:");
        ventesLB.setToolTipText("Clicker ici pour afficher les détails");
        ventesLB.setFocusable(false);
        ventesLB.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        ventesLB.setOpaque(true);
        ventesLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventesLBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        totalsPanel.add(ventesLB, gridBagConstraints);

        recettePanel.setOpaque(true);
        recettePanel.setTitleIcon("\"\"");
        recettePanel.setTitleString("");
        recettePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recettePanelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        totalsPanel.add(recettePanel, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Crédit:");
        jLabel5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        totalsPanel.add(jLabel5, gridBagConstraints);

        creditPanel.setOpaque(true);
        creditPanel.setTitleIcon("\"\"");
        creditPanel.setTitleString("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        totalsPanel.add(creditPanel, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Dépenses:");
        jLabel3.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        totalsPanel.add(jLabel3, gridBagConstraints);

        depensePanel.setOpaque(true);
        depensePanel.setTitleIcon("\"\"");
        depensePanel.setTitleString("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        totalsPanel.add(depensePanel, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Caisse:");
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        totalsPanel.add(jLabel2, gridBagConstraints);

        caissePanel.setOpaque(true);
        caissePanel.setTitleIcon("\"\"");
        caissePanel.setTitleString("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        totalsPanel.add(caissePanel, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Bénifices des Ventes:");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        totalsPanel.add(jLabel4, gridBagConstraints);

        benificePanel.setComponentPopupMenu(benifMenu);
        benificePanel.setOpaque(true);
        benificePanel.setTitleIcon("\"\"");
        benificePanel.setTitleString("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        totalsPanel.add(benificePanel, gridBagConstraints);

        jSplitPane1.setLeftComponent(totalsPanel);
        jSplitPane1.setRightComponent(detailsTab);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void recettePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recettePanelMouseClicked

    }//GEN-LAST:event_recettePanelMouseClicked

    private void ventesLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventesLBActionPerformed
        //detailsPanel.add(journalVentesPanel);
    }//GEN-LAST:event_ventesLBActionPerformed

    private void showBenifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBenifActionPerformed
        showBenif(true);
    }//GEN-LAST:event_showBenifActionPerformed

    private void hideBenifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideBenifActionPerformed
        showBenif(false);
    }//GEN-LAST:event_hideBenifActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu benifMenu;
    private panels.views.MontantPanel benificePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private panels.views.MontantPanel caissePanel;
    private panels.views.MontantPanel creditPanel;
    private panels.views.MontantPanel depensePanel;
    private javax.swing.JTabbedPane detailsTab;
    private javax.swing.JMenuItem hideBenif;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSplitPane jSplitPane1;
    private panels.views.MontantPanel recettePanel;
    private javax.swing.JMenuItem showBenif;
    private javax.swing.JPanel totalsPanel;
    private com.l2fprod.common.swing.JLinkButton ventesLB;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        MyJFrame frame = new MyJFrame();
        //frame.setExtendedState(Frame.MAXIMIZED_BOTH);
        frame.setTitle("Recette");
        frame.getContentPane().add(new StatistiquesPanel(), BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
}
