/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.masterDetails;

import javax.swing.JSplitPane;
import myComponents.MyJFrame;
import panels.MasterDetailsPanel;
import panels.crud.ListeCategoriesPanel;
import panels.crud.ListeFamillesPanel;
import panels.crud.ListeLotsEnStockPanel;
import panels.crud.ListeProduitsPanel;

/**
 *
 * @author alilo
 */
public class GestStockPanel extends MasterDetailsPanel {

    private static final String CAT_SPLIT_POS = "mainLotCatSplitPos";
    private static final String PROD_SPLIT_POS = "mainLotProdSplitPos";

    ListeFamillesPanel famillesPanel;
    ListeCategoriesPanel categoriesPanel;
    ListeLotsEnStockPanel lotsPanel;

    /**
     * Creates new form MainProduitPanel
     *
     * @param famP
     * @param catP
     * @param lotP
     */
    public GestStockPanel(ListeFamillesPanel famP, ListeCategoriesPanel catP, ListeLotsEnStockPanel lotP) {
        initComponents();
        if (famP == null) {
            famillesPanel = new ListeFamillesPanel(this, false) {

                @Override
                public ListeFamillesPanel initTableView() {
                    super.initTableView();
                    getTable().setColumnVisible("TVA %", false);
                    return this; 
                }
                
                @Override
                public void reload() {
                    super.reload();
                    categoriesPanel.reload();
                }
            };
        } else {
            famillesPanel = famP;
            famillesPanel.setOwnerPanel(GestStockPanel.this);
        }

        if (catP == null) {
            categoriesPanel = new ListeCategoriesPanel(this, false) {
                @Override
                public void reload() {
                    super.reload();
                    lotsPanel.reload();
                }

            };
        } else {
            categoriesPanel = catP;
            categoriesPanel.setOwnerPanel(GestStockPanel.this);
        }

        if (lotP == null) {
            lotsPanel = new ListeLotsEnStockPanel(this, false);
        } else {
            lotsPanel = lotP;
            lotsPanel.setOwnerPanel(GestStockPanel.this);
        }
        
        categoriesPanel.setMasterPanel(famillesPanel, null);
        lotsPanel.setMasterPanel(categoriesPanel, "ID_CATEG");
        lotsPanel.setMasterPanel(famillesPanel, "ID_FAM");

        prodHolderP.add(lotsPanel);
        categHolderP.add(categoriesPanel);
        famHolderP.add(famillesPanel);

        categSplitPan.setDividerLocation(getUserPreferences().getInt(CAT_SPLIT_POS, 350));
        prodSplitPan.setDividerLocation(getUserPreferences().getInt(PROD_SPLIT_POS, 250));

    }

    @Override
    public void reload() {
        famillesPanel.reload();
    }

    @Override
    public void doFilter() {
        lotsPanel.doFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prodSplitPan = new javax.swing.JSplitPane();
        categSplitPan = new javax.swing.JSplitPane();
        famHolderP = new javax.swing.JPanel();
        categHolderP = new javax.swing.JPanel();
        prodHolderP = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        prodSplitPan.setOneTouchExpandable(true);
        prodSplitPan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                prodSplitPanPropertyChange(evt);
            }
        });

        categSplitPan.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        categSplitPan.setOneTouchExpandable(true);
        categSplitPan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                categSplitPanPropertyChange(evt);
            }
        });

        famHolderP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Familles (Ctrl+F) ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        famHolderP.setPreferredSize(new java.awt.Dimension(250, 250));
        famHolderP.setLayout(new java.awt.BorderLayout());
        categSplitPan.setLeftComponent(famHolderP);

        categHolderP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Catégories (Ctrl+T)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        categHolderP.setLayout(new java.awt.BorderLayout());
        categSplitPan.setRightComponent(categHolderP);

        prodSplitPan.setLeftComponent(categSplitPan);

        prodHolderP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Produits (Ctrl+R) ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        prodHolderP.setPreferredSize(new java.awt.Dimension(600, 28));
        prodHolderP.setLayout(new java.awt.BorderLayout());
        prodSplitPan.setRightComponent(prodHolderP);

        add(prodSplitPan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void prodSplitPanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_prodSplitPanPropertyChange
        if (evt.getPropertyName().equals(JSplitPane.DIVIDER_LOCATION_PROPERTY)) {
            savePreference(PROD_SPLIT_POS, prodSplitPan.getDividerLocation());
        }
    }//GEN-LAST:event_prodSplitPanPropertyChange

    private void categSplitPanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_categSplitPanPropertyChange
        if (evt.getPropertyName().equals(JSplitPane.DIVIDER_LOCATION_PROPERTY)) {
            savePreference(CAT_SPLIT_POS, categSplitPan.getDividerLocation());
        }
    }//GEN-LAST:event_categSplitPanPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categHolderP;
    private javax.swing.JSplitPane categSplitPan;
    private javax.swing.JPanel famHolderP;
    private javax.swing.JPanel prodHolderP;
    private javax.swing.JSplitPane prodSplitPan;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MyJFrame frame = new MyJFrame();
                frame.setTitle("Test");
                frame.add(new GestStockPanel(null, null, null));
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
